import Cantilune.Feedback.EventTrajectoryRandomized

/-!
# Production-kernel trajectory agreement

This module couples two caller-supplied finite native Markov kernels at the
level of their genuine Ionescu--Tulcea trajectory laws.  It does not replace
either kernel by the canonical deterministic replay scheduler.

A production coupling has one joint probability measure whose two exact
marginals are the randomized event-trajectory measures generated by the
supplied kernels.  A separate seam states the product-specific facts that
probability theory cannot infer: related states, common event marks, a shared
action interpretation, and aligned external epochs/signature versions.

The main theorem derives, almost surely under the joint law:

* both genuine state trajectories and their stable-set hitting conclusions;
* native event-labelled steps on both sides;
* exact `DPOEvent` replay at every pair of endpoints;
* common event marks and shared action labels;
* aligned, strictly increasing external epochs; and
* aligned signature versions.

No production-package inhabitant is constructed here.  A package must supply
its kernels, progress bridges, seed laws, coupling, and semantic seam.
-/

noncomputable section

namespace Cantilune.Feedback.ProductionKernelTrajectoryAgreement

open MeasureTheory
open Cantilune.Core
open Cantilune.Feedback.Probability
open Cantilune.Feedback.StochasticExecution
open Cantilune.Feedback.StochasticExecution.FiniteDiscrete
open Cantilune.Feedback.EventTrajectory
open Cantilune.Feedback.EventTrajectory.FiniteDiscrete

universe uLeftState uRightState uLeftSeed uRightSeed uMark uAction

variable
    {leftSignature rightSignature : FinSignature}
    {leftPackage : ExecutionPackage leftSignature}
    {rightPackage : ExecutionPackage rightSignature}
    {LeftState : Type uLeftState}
    [Fintype LeftState] [DecidableEq LeftState]
    [MeasurableSpace LeftState] [MeasurableSingletonClass LeftState]
    {RightState : Type uRightState}
    [Fintype RightState] [DecidableEq RightState]
    [MeasurableSpace RightState] [MeasurableSingletonClass RightState]
    {LeftSeed : Type uLeftSeed} [MeasurableSpace LeftSeed]
    {RightSeed : Type uRightSeed} [MeasurableSpace RightSeed]
    {leftKernel :
      NativeMarkovKernel leftSignature leftPackage LeftState}
    {rightKernel :
      NativeMarkovKernel rightSignature rightPackage RightState}
    {leftInitial : InitialDistribution LeftState}
    {rightInitial : InitialDistribution RightState}
    {leftEpsilon rightEpsilon : Real}

/-- One joint sample contains both state paths and both event-seed paths. -/
abbrev CoupledTrajectorySample
    (LeftState : Type uLeftState) (LeftSeed : Type uLeftSeed)
    (RightState : Type uRightState) (RightSeed : Type uRightSeed) :=
  RandomizedEventPath LeftState LeftSeed ×
    RandomizedEventPath RightState RightSeed

/--
A genuine coupling of two supplied randomized event-trajectory laws.

The marginal equalities are deliberately exact equalities of measures.  A
mere relation between endpoint distributions is not enough to recover
event-labelled infinite trajectories.
-/
structure ProductionTrajectoryCoupling
    (leftBridge :
      RandomEventProgressBridge
        leftKernel leftInitial leftEpsilon LeftSeed)
    (leftSeedMeasure : Measure (Nat → LeftSeed))
    (rightBridge :
      RandomEventProgressBridge
        rightKernel rightInitial rightEpsilon RightSeed)
    (rightSeedMeasure : Measure (Nat → RightSeed)) where
  joint :
    Measure
      (CoupledTrajectorySample
        LeftState LeftSeed RightState RightSeed)
  joint_probability : IsProbabilityMeasure joint
  left_marginal :
    joint.map Prod.fst =
      randomizedEventTrajectoryMeasure leftBridge leftSeedMeasure
  right_marginal :
    joint.map Prod.snd =
      randomizedEventTrajectoryMeasure rightBridge rightSeedMeasure

namespace ProductionTrajectoryCoupling

variable
    (leftBridge :
      RandomEventProgressBridge
        leftKernel leftInitial leftEpsilon LeftSeed)
    (leftSeedMeasure : Measure (Nat → LeftSeed))
    (rightBridge :
      RandomEventProgressBridge
        rightKernel rightInitial rightEpsilon RightSeed)
    (rightSeedMeasure : Measure (Nat → RightSeed))

instance
    (coupling :
      ProductionTrajectoryCoupling
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure) :
    IsProbabilityMeasure coupling.joint :=
  coupling.joint_probability

/--
The product of the two genuine path laws is always a coupling.  This
constructor is useful when no cross-row correlation is required; correlated
production couplings may supply a different `joint` measure.
-/
def independent
    [IsProbabilityMeasure leftSeedMeasure]
    [IsProbabilityMeasure rightSeedMeasure] :
    ProductionTrajectoryCoupling
      leftBridge leftSeedMeasure rightBridge rightSeedMeasure where
  joint :=
    (randomizedEventTrajectoryMeasure leftBridge leftSeedMeasure).prod
      (randomizedEventTrajectoryMeasure rightBridge rightSeedMeasure)
  joint_probability := inferInstance
  left_marginal := by
    rw [Measure.map_fst_prod, measure_univ, one_smul]
  right_marginal := by
    rw [Measure.map_snd_prod, measure_univ, one_smul]

variable
    {leftBridge leftSeedMeasure rightBridge rightSeedMeasure}
    (coupling :
      ProductionTrajectoryCoupling
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure)

/-- Transfer a measurable left-path almost-sure property through the coupling. -/
theorem left_ae_of_marginal
    {predicate : RandomizedEventPath LeftState LeftSeed → Prop}
    (measurablePredicate : MeasurableSet {path | predicate path})
    (almostSure :
      ∀ᵐ path
        ∂randomizedEventTrajectoryMeasure leftBridge leftSeedMeasure,
        predicate path) :
    ∀ᵐ sample ∂coupling.joint, predicate sample.1 := by
  have mapped :
      ∀ᵐ path ∂coupling.joint.map Prod.fst, predicate path := by
    rw [coupling.left_marginal]
    exact almostSure
  exact
    (ae_map_iff measurable_fst.aemeasurable measurablePredicate).1 mapped

/-- Transfer a measurable right-path almost-sure property through the coupling. -/
theorem right_ae_of_marginal
    {predicate : RandomizedEventPath RightState RightSeed → Prop}
    (measurablePredicate : MeasurableSet {path | predicate path})
    (almostSure :
      ∀ᵐ path
        ∂randomizedEventTrajectoryMeasure rightBridge rightSeedMeasure,
        predicate path) :
    ∀ᵐ sample ∂coupling.joint, predicate sample.2 := by
  have mapped :
      ∀ᵐ path ∂coupling.joint.map Prod.snd, predicate path := by
    rw [coupling.right_marginal]
    exact almostSure
  exact
    (ae_map_iff measurable_snd.aemeasurable measurablePredicate).1 mapped

end ProductionTrajectoryCoupling

/-- Measurability of stable-set hitting on a randomized event path. -/
theorem measurable_randomized_eventuallyHits
    (bridge :
      RandomEventProgressBridge
        leftKernel leftInitial leftEpsilon LeftSeed) :
    MeasurableSet
      {path : RandomizedEventPath LeftState LeftSeed |
        bridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
          path.1} := by
  have measurableNeverHit :
      MeasurableSet
        bridge.progress.toKernelProgressAssumption.hittingBridge.neverHit :=
    MeasurableSet.iInter
      (bridge.progress.toKernelProgressAssumption.hittingBridge
        |>.measurable_notHit)
  have measurableStateHitting :
      MeasurableSet
        {path : Nat → LeftState |
          bridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
            path} := by
    have setEquality :
        {path : Nat → LeftState |
          bridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
            path} =
          bridge.progress.toKernelProgressAssumption.hittingBridge.neverHitᶜ := by
      ext path
      exact
        bridge.progress.toKernelProgressAssumption.hittingBridge
          |>.eventuallyHits_iff_not_mem_neverHit path
    rw [setEquality]
    exact measurableNeverHit.compl
  exact measurableStateHitting.preimage measurable_fst

section CoupledAgreement

variable
    (leftBridge :
      RandomEventProgressBridge
        leftKernel leftInitial leftEpsilon LeftSeed)
    (leftSeedMeasure : Measure (Nat → LeftSeed))
    [IsProbabilityMeasure leftSeedMeasure]
    (rightBridge :
      RandomEventProgressBridge
        rightKernel rightInitial rightEpsilon RightSeed)
    (rightSeedMeasure : Measure (Nat → RightSeed))
    [IsProbabilityMeasure rightSeedMeasure]
    (coupling :
      ProductionTrajectoryCoupling
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure)

/--
The semantic information shared by two production rows.

`Mark` may be a replay identifier or product event key.  `Action` may be the
common FMS action type.  Factoring both event interpretations through
`markAction` makes action equality a theorem of mark equality rather than a
second unrelated premise.
-/
structure ReplayMarkActionEpochSeam
    (Mark : Type uMark)
    (Action : Type uAction)
    (StateRelation : LeftState → RightState → Prop) where
  leftMark : leftPackage.lts.Event → Mark
  rightMark : rightPackage.lts.Event → Mark
  markAction : Mark → Action
  leftAction : leftPackage.lts.Event → Action
  rightAction : rightPackage.lts.Event → Action
  leftAction_factors :
    ∀ event, leftAction event = markAction (leftMark event)
  rightAction_factors :
    ∀ event, rightAction event = markAction (rightMark event)
  states_related :
    ∀ᵐ sample ∂coupling.joint,
      ∀ n, StateRelation (sample.1.1 n) (sample.2.1 n)
  marks_agree :
    ∀ᵐ sample ∂coupling.joint,
      ∀ n,
        leftMark
            ((RandomizedEventPath.trajectory leftBridge sample.1).event n) =
          rightMark
            ((RandomizedEventPath.trajectory rightBridge sample.2).event n)
  epochs_agree :
    ∀ n,
      eventEpoch leftBridge.progress.window n =
        eventEpoch rightBridge.progress.window n
  signature_versions_agree :
    ∀ n,
      leftBridge.progress.window.signatureVersion
          (eventEpoch leftBridge.progress.window n) =
        rightBridge.progress.window.signatureVersion
          (eventEpoch rightBridge.progress.window n)

variable
    {Mark : Type uMark}
    {Action : Type uAction}
    {StateRelation : LeftState → RightState → Prop}
    (seam :
      ReplayMarkActionEpochSeam
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure coupling
        Mark Action StateRelation)

/--
The complete event-level agreement obtained for one coupled sample.

All native and replay fields are derived from the supplied execution packages
and randomized event labellings.  The only product-specific fields are the
relations recorded by `ReplayMarkActionEpochSeam`.
-/
structure CompleteProductionTrajectoryAgreement
    (sample :
      CoupledTrajectorySample
        LeftState LeftSeed RightState RightSeed) : Prop where
  left_state_projection :
    TotalNativeLabelling.projectState
        (kernel := leftKernel)
        (RandomizedEventPath.trajectory leftBridge sample.1) =
      sample.1.1
  right_state_projection :
    TotalNativeLabelling.projectState
        (kernel := rightKernel)
        (RandomizedEventPath.trajectory rightBridge sample.2) =
      sample.2.1
  left_native :
    ∀ n,
      leftPackage.lts.ObservableStep
        ((RandomizedEventPath.trajectory leftBridge sample.1).state n)
        ((RandomizedEventPath.trajectory leftBridge sample.1).event n)
        ((RandomizedEventPath.trajectory leftBridge sample.1).state (n + 1))
  right_native :
    ∀ n,
      rightPackage.lts.ObservableStep
        ((RandomizedEventPath.trajectory rightBridge sample.2).state n)
        ((RandomizedEventPath.trajectory rightBridge sample.2).event n)
        ((RandomizedEventPath.trajectory rightBridge sample.2).state (n + 1))
  left_replays :
    ∀ n,
      (leftPackage.eventRecord
          ((RandomizedEventPath.trajectory leftBridge sample.1).event n)).Replays
        (leftPackage.configOf
          ((RandomizedEventPath.trajectory leftBridge sample.1).state n))
        (leftPackage.configOf
          ((RandomizedEventPath.trajectory leftBridge sample.1).state (n + 1)))
  right_replays :
    ∀ n,
      (rightPackage.eventRecord
          ((RandomizedEventPath.trajectory rightBridge sample.2).event n)).Replays
        (rightPackage.configOf
          ((RandomizedEventPath.trajectory rightBridge sample.2).state n))
        (rightPackage.configOf
          ((RandomizedEventPath.trajectory rightBridge sample.2).state (n + 1)))
  left_epoch_aligned :
    EpochAlignedTrajectory leftBridge.progress.window
      (RandomizedEventPath.trajectory leftBridge sample.1)
  right_epoch_aligned :
    EpochAlignedTrajectory rightBridge.progress.window
      (RandomizedEventPath.trajectory rightBridge sample.2)
  states_related :
    ∀ n, StateRelation (sample.1.1 n) (sample.2.1 n)
  marks_agree :
    ∀ n,
      seam.leftMark
          ((RandomizedEventPath.trajectory leftBridge sample.1).event n) =
        seam.rightMark
          ((RandomizedEventPath.trajectory rightBridge sample.2).event n)
  actions_agree :
    ∀ n,
      seam.leftAction
          ((RandomizedEventPath.trajectory leftBridge sample.1).event n) =
        seam.rightAction
          ((RandomizedEventPath.trajectory rightBridge sample.2).event n)
  epochs_agree :
    ∀ n,
      eventEpoch leftBridge.progress.window n =
        eventEpoch rightBridge.progress.window n
  left_epoch_strict :
    ∀ n, EpochBoundary leftBridge.progress.window n
  right_epoch_strict :
    ∀ n, EpochBoundary rightBridge.progress.window n
  signature_versions_agree :
    ∀ n,
      leftBridge.progress.window.signatureVersion
          (eventEpoch leftBridge.progress.window n) =
        rightBridge.progress.window.signatureVersion
          (eventEpoch rightBridge.progress.window n)
  left_eventually_hits :
    leftBridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
      sample.1.1
  right_eventually_hits :
    rightBridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
      sample.2.1

omit [IsProbabilityMeasure rightSeedMeasure] in
/-- The left kernel's genuine hitting theorem lifts through the joint law. -/
theorem left_eventually_hits_almost_sure :
    ∀ᵐ sample ∂coupling.joint,
      leftBridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
        sample.1.1 := by
  exact
    coupling.left_ae_of_marginal
      (predicate := fun path =>
        leftBridge.progress.toKernelProgressAssumption.hittingBridge
          |>.EventuallyHits path.1)
      (measurable_randomized_eventuallyHits leftBridge)
      (randomized_event_measure_almost_sure_hitting
        leftBridge leftSeedMeasure)

omit [IsProbabilityMeasure leftSeedMeasure] in
/-- The right kernel's genuine hitting theorem lifts through the joint law. -/
theorem right_eventually_hits_almost_sure :
    ∀ᵐ sample ∂coupling.joint,
      rightBridge.progress.toKernelProgressAssumption.hittingBridge.EventuallyHits
        sample.2.1 := by
  exact
    coupling.right_ae_of_marginal
      (predicate := fun path =>
        rightBridge.progress.toKernelProgressAssumption.hittingBridge
          |>.EventuallyHits path.1)
      (measurable_randomized_eventuallyHits rightBridge)
      (randomized_event_measure_almost_sure_hitting
        rightBridge rightSeedMeasure)

/--
Production-strength trajectory agreement for two supplied stochastic kernels.

The theorem is quantified over the actual joint coupling measure.  It does
not mention the canonical marked replay kernel and does not assume that the
two kernels are equal or deterministic.
-/
theorem complete_production_trajectory_agreement_almost_sure :
    ∀ᵐ sample ∂coupling.joint,
      CompleteProductionTrajectoryAgreement
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure
        coupling seam sample := by
  filter_upwards
    [seam.states_related, seam.marks_agree,
      left_eventually_hits_almost_sure
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure coupling,
      right_eventually_hits_almost_sure
        leftBridge leftSeedMeasure rightBridge rightSeedMeasure coupling]
      with sample statesRelated marksAgree leftHits rightHits
  refine
    { left_state_projection :=
        RandomizedEventPath.trajectory_state_projection
          leftBridge sample.1
      right_state_projection :=
        RandomizedEventPath.trajectory_state_projection
          rightBridge sample.2
      left_native := RandomizedEventPath.native leftBridge sample.1
      right_native := RandomizedEventPath.native rightBridge sample.2
      left_replays := RandomizedEventPath.replays leftBridge sample.1
      right_replays := RandomizedEventPath.replays rightBridge sample.2
      left_epoch_aligned :=
        leftBridge.alignment.decorate_aligned sample.1.1 sample.1.2
      right_epoch_aligned :=
        rightBridge.alignment.decorate_aligned sample.2.1 sample.2.2
      states_related := statesRelated
      marks_agree := marksAgree
      actions_agree := ?_
      epochs_agree := seam.epochs_agree
      left_epoch_strict := every_step_has_epoch_boundary _
      right_epoch_strict := every_step_has_epoch_boundary _
      signature_versions_agree := seam.signature_versions_agree
      left_eventually_hits := leftHits
      right_eventually_hits := rightHits }
  intro n
  calc
    seam.leftAction
        ((RandomizedEventPath.trajectory leftBridge sample.1).event n) =
        seam.markAction
          (seam.leftMark
            ((RandomizedEventPath.trajectory leftBridge sample.1).event n)) :=
      seam.leftAction_factors _
    _ =
        seam.markAction
          (seam.rightMark
            ((RandomizedEventPath.trajectory rightBridge sample.2).event n)) :=
      congrArg seam.markAction (marksAgree n)
    _ =
        seam.rightAction
          ((RandomizedEventPath.trajectory rightBridge sample.2).event n) :=
      (seam.rightAction_factors _).symm

end CoupledAgreement

end Cantilune.Feedback.ProductionKernelTrajectoryAgreement
