import Cantilune.Pi.FMSCpoScottClosedPower
import Mathlib.Topology.Continuous

/-!
# The omega-Scott closed-set power construction

This file equips every omega-CPO with the Scott topology generated by ranges
of omega-chains, rather than the full directed Scott topology.  With that
choice, every mathlib `ContinuousHom` is also topologically continuous.

The distinction is load-bearing: the full-Scott construction in
`FMSCpoScottClosedPower` requires a stronger topological continuity
hypothesis for direct image.  The omega-Scott topology is chosen so every
morphism of `ωCPO` supplies the topological continuity needed below.

This remains a lower/Hoare-style closed-set construction.  Nothing in this
file identifies it with the Abramsky powerdomain or establishes the FMS
domain equation or full abstraction.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoOmegaScottPower

open CategoryTheory
open OmegaCompletePartialOrder
open Set
open Topology

universe u

/-! ## The omega-Scott topology -/

/-- Ranges of designated omega-chains. -/
def omegaChainRanges
    (α : Type u) [Preorder α] :
    Set (Set α) :=
  Set.range fun chain : Chain α => Set.range chain

/-- Type synonym carrying the Scott topology generated by omega-chain ranges. -/
def WithOmegaScott
    (α : Type u) :=
  α

namespace WithOmegaScott

def toOmegaScott :
    α ≃ WithOmegaScott α :=
  Equiv.refl _

def ofOmegaScott :
    WithOmegaScott α ≃ α :=
  Equiv.refl _

@[simp]
theorem toOmegaScott_ofOmegaScott
    (value : WithOmegaScott α) :
    toOmegaScott (ofOmegaScott value) = value :=
  rfl

@[simp]
theorem ofOmegaScott_toOmegaScott
    (value : α) :
    ofOmegaScott (toOmegaScott value) = value :=
  rfl

instance [PartialOrder α] :
    PartialOrder (WithOmegaScott α) :=
  inferInstanceAs (PartialOrder α)

instance [OmegaCompletePartialOrder α] :
    OmegaCompletePartialOrder (WithOmegaScott α) :=
  inferInstanceAs (OmegaCompletePartialOrder α)

instance [OmegaCompletePartialOrder α] :
    TopologicalSpace (WithOmegaScott α) :=
  Topology.scott
    (WithOmegaScott α)
    (omegaChainRanges (WithOmegaScott α))

instance [OmegaCompletePartialOrder α] :
    Topology.IsScott
      (WithOmegaScott α)
      (Set.range fun chain : Chain (WithOmegaScott α) =>
        Set.range chain) :=
  ⟨rfl⟩

end WithOmegaScott

/-- Lift a function between carriers to the omega-Scott type synonyms. -/
def omegaScottLift
    {α β : Type u}
    (function : α → β) :
    WithOmegaScott α → WithOmegaScott β :=
  fun value =>
    WithOmegaScott.toOmegaScott
      (function (WithOmegaScott.ofOmegaScott value))

theorem omegaScottLift_omegaScottContinuous
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α → β)
    (continuous : ωScottContinuous function) :
    ωScottContinuous (omegaScottLift function) :=
  continuous

/--
An omega-Scott continuous map is continuous between the corresponding
omega-Scott topologies.

The proof uses characteristic functions of open sets.  Their
omega-continuity composes with the given map and is converted back to
topological continuity by mathlib's omega-Scott/Prop equivalence.
-/
theorem omegaScottLift_continuous
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α → β)
    (omegaContinuous : ωScottContinuous function) :
    Continuous (omegaScottLift function) := by
  rw [continuous_def]
  intro target targetOpen
  rw [isOpen_iff_continuous_mem] at targetOpen ⊢
  have targetMembershipOmega :
      ωScottContinuous
        (fun value : WithOmegaScott β => value ∈ target) :=
    (Topology.IsScott.ωScottContinuous_iff_continuous
      (α := WithOmegaScott β)).2
      targetOpen
  have liftedOmega :
      ωScottContinuous (omegaScottLift function) :=
    omegaScottLift_omegaScottContinuous
      function omegaContinuous
  exact
    (Topology.IsScott.ωScottContinuous_iff_continuous
      (α := WithOmegaScott α)).1
      (targetMembershipOmega.comp liftedOmega)

/-- Every `ContinuousHom` is continuous for the omega-Scott topologies. -/
theorem continuousHom_omegaScott_continuous
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β) :
    Continuous (omegaScottLift function) :=
  omegaScottLift_continuous
    function function.ωScottContinuous

/-! ## Omega-Scott closed computations -/

/-- Closed sets of the omega-Scott topology, ordered by inclusion. -/
abbrev OmegaScottPower
    (α : Type u) [OmegaCompletePartialOrder α] :=
  TopologicalSpace.Closeds (WithOmegaScott α)

def carrier
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    Set (WithOmegaScott α) :=
  values

/-- Closed-set characterization for the omega-chain Scott topology. -/
theorem isClosed_iff_isLowerSet_and_chainSupClosed
    {α : Type u} [OmegaCompletePartialOrder α]
    {values : Set (WithOmegaScott α)} :
    IsClosed values ↔
      IsLowerSet values ∧
        DirSupClosedOn
          (Set.range fun chain : Chain (WithOmegaScott α) =>
            Set.range chain)
          values := by
  rw [← isOpen_compl_iff]
  rw [Topology.IsScott.isOpen_iff_isUpperSet_and_dirSupInaccOn
    (D :=
      Set.range fun chain : Chain (WithOmegaScott α) =>
        Set.range chain)]
  rw [isUpperSet_compl, dirSupInaccOn_compl]

theorem isLowerSet
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    IsLowerSet (carrier values) :=
  (isClosed_iff_isLowerSet_and_chainSupClosed.mp
    values.isClosed).1

theorem chainSupClosed
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    DirSupClosedOn
      (Set.range fun chain : Chain (WithOmegaScott α) =>
        Set.range chain)
      (carrier values) :=
  (isClosed_iff_isLowerSet_and_chainSupClosed.mp
    values.isClosed).2

/-- The closed-set complete lattice is an omega-CPO. -/
abbrev omegaScottPowerCpo
    (α : Type u) [OmegaCompletePartialOrder α] :
    ωCPO :=
  ωCPO.of (OmegaScottPower α)

theorem omegaSup_mem
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α)
    (chain : Chain α)
    (members :
      ∀ index,
        WithOmegaScott.toOmegaScott (chain index) ∈
          carrier values) :
    WithOmegaScott.toOmegaScott (ωSup chain) ∈
      carrier values := by
  let liftedChain : Chain (WithOmegaScott α) :=
    { toFun := fun index =>
        WithOmegaScott.toOmegaScott (chain index)
      monotone' := chain.monotone }
  refine
    (chainSupClosed values)
      (d := Set.range liftedChain)
      ⟨liftedChain, rfl⟩ ?_ ?_ ?_ ?_
  · rintro value ⟨index, rfl⟩
    exact members index
  · exact ⟨liftedChain 0, ⟨0, rfl⟩⟩
  · exact liftedChain.isChain_range.directedOn
  · apply Scott.isωSup_iff_isLUB.mp
    constructor
    · intro index
      exact le_ωSup chain index
    · intro upper isUpper
      exact
        ωSup_le chain
          (WithOmegaScott.ofOmegaScott upper)
          isUpper

/-! ## Chain suprema and principal return -/

def omegaSupCandidate
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain : Chain (OmegaScottPower α)) :
    OmegaScottPower α :=
  TopologicalSpace.Closeds.closure
    (⋃ index, carrier (chain index))

theorem le_omegaSupCandidate
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain : Chain (OmegaScottPower α)) (index : ℕ) :
    chain index ≤ omegaSupCandidate chain := by
  intro value valueMember
  exact
    subset_closure
      (mem_iUnion.2
        ⟨index,
          show value ∈ carrier (chain index)
            from valueMember⟩)

theorem omegaSupCandidate_le
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain : Chain (OmegaScottPower α))
    (upper : OmegaScottPower α)
    (isUpper : ∀ index, chain index ≤ upper) :
    omegaSupCandidate chain ≤ upper := by
  change
    TopologicalSpace.Closeds.closure
        (⋃ index, carrier (chain index)) ≤ upper
  rw [TopologicalSpace.Closeds.closure_le]
  intro value valueMember
  obtain ⟨index, memberAtIndex⟩ :=
    mem_iUnion.mp valueMember
  exact isUpper index memberAtIndex

theorem omegaSup_eq_closure_iUnion
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain : Chain (OmegaScottPower α)) :
    ωSup chain = omegaSupCandidate chain := by
  apply le_antisymm
  · apply ωSup_le
    exact le_omegaSupCandidate chain
  · apply omegaSupCandidate_le
    exact le_ωSup chain

theorem isClosed_Iic
    {α : Type u} [OmegaCompletePartialOrder α]
    (value : WithOmegaScott α) :
    IsClosed (Iic value) :=
  isClosed_iff_isLowerSet_and_chainSupClosed.mpr
    ⟨isLowerSet_Iic value, dirSupClosedOn_Iic value⟩

def principalRaw
    {α : Type u} [OmegaCompletePartialOrder α]
    (value : α) :
    OmegaScottPower α :=
  ⟨Iic (WithOmegaScott.toOmegaScott value),
    isClosed_Iic _⟩

@[simp]
theorem mem_principalRaw_iff
    {α : Type u} [OmegaCompletePartialOrder α]
    (left right : α) :
    WithOmegaScott.toOmegaScott left ∈
        carrier (principalRaw right) ↔
      left ≤ right :=
  Iff.rfl

theorem principalRaw_monotone
    {α : Type u} [OmegaCompletePartialOrder α] :
    Monotone
      (principalRaw : α → OmegaScottPower α) := by
  intro left right ordered value valueLe
  exact le_trans valueLe ordered

def principalOrderHom
    {α : Type u} [OmegaCompletePartialOrder α] :
    α →o OmegaScottPower α where
  toFun := principalRaw
  monotone' := principalRaw_monotone

theorem principalRaw_map_omegaSup
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain : Chain α) :
    principalRaw (ωSup chain) =
      ωSup (chain.map principalOrderHom) := by
  apply le_antisymm
  · intro value valueLe
    have pointMember :
        ∀ index,
          WithOmegaScott.toOmegaScott (chain index) ∈
            carrier
              (ωSup (chain.map principalOrderHom)) := by
      intro index
      have inclusion :
          principalRaw (chain index) ≤
            ωSup (chain.map principalOrderHom) :=
        le_ωSup (chain.map principalOrderHom) index
      exact inclusion le_rfl
    have limitMember :
        WithOmegaScott.toOmegaScott (ωSup chain) ∈
          carrier
            (ωSup (chain.map principalOrderHom)) :=
      omegaSup_mem
        (ωSup (chain.map principalOrderHom))
        chain pointMember
    change
      value ∈
        carrier (ωSup (chain.map principalOrderHom))
    exact
      isLowerSet
        (ωSup (chain.map principalOrderHom))
        valueLe limitMember
  · apply ωSup_le
    intro index
    exact principalRaw_monotone (le_ωSup chain index)

def principal
    {α : Type u} [OmegaCompletePartialOrder α] :
    ωCPO.of α ⟶ omegaScottPowerCpo α where
  toFun := principalRaw
  monotone' := principalRaw_monotone
  map_ωSup' := principalRaw_map_omegaSup

/-! ## Choice and unseparated flattening -/

def choice
    {α : Type u} [OmegaCompletePartialOrder α] :
    ωCPO.of
        (OmegaScottPower α × OmegaScottPower α) ⟶
      omegaScottPowerCpo α :=
  ContinuousHom.ofFun
    (fun pair : OmegaScottPower α ×
        OmegaScottPower α =>
      pair.1 ⊔ pair.2)
    (CompleteLattice.ωScottContinuous.sup
      Prod.ωScottContinuous_fst
      Prod.ωScottContinuous_snd)

def memberSet
    {α : Type u} [OmegaCompletePartialOrder α]
    (family : OmegaScottPower (OmegaScottPower α)) :
    Set (OmegaScottPower α) :=
  WithOmegaScott.ofOmegaScott '' carrier family

@[simp]
theorem mem_memberSet_iff
    {α : Type u} [OmegaCompletePartialOrder α]
    (family : OmegaScottPower (OmegaScottPower α))
    (values : OmegaScottPower α) :
    values ∈ memberSet family ↔
      WithOmegaScott.toOmegaScott values ∈
        carrier family := by
  constructor
  · rintro ⟨lifted, member, equality⟩
    simpa [← equality] using member
  · intro member
    exact
      ⟨WithOmegaScott.toOmegaScott values, member,
        WithOmegaScott.ofOmegaScott_toOmegaScott values⟩

def flattenRaw
    {α : Type u} [OmegaCompletePartialOrder α]
    (family : OmegaScottPower (OmegaScottPower α)) :
    OmegaScottPower α :=
  sSup (memberSet family)

theorem flattenRaw_le_iff
    {α : Type u} [OmegaCompletePartialOrder α]
    (family : OmegaScottPower (OmegaScottPower α))
    (bound : OmegaScottPower α) :
    flattenRaw family ≤ bound ↔
      family ≤ principalRaw bound := by
  constructor
  · intro flattenedLe value valueMember
    change WithOmegaScott.ofOmegaScott value ≤ bound
    exact
      le_trans
        (le_sSup
          ((mem_memberSet_iff family
            (WithOmegaScott.ofOmegaScott value)).2
            valueMember))
        flattenedLe
  · intro familyLe
    apply sSup_le
    intro values valuesMember
    have member :
        WithOmegaScott.toOmegaScott values ∈
          carrier family :=
      (mem_memberSet_iff family values).1
        valuesMember
    exact familyLe member

theorem flattenRaw_monotone
    {α : Type u} [OmegaCompletePartialOrder α] :
    Monotone
      (flattenRaw :
        OmegaScottPower (OmegaScottPower α) →
          OmegaScottPower α) := by
  intro left right ordered
  apply
    (flattenRaw_le_iff
      left (flattenRaw right)).2
  exact le_trans ordered
    ((flattenRaw_le_iff
      right (flattenRaw right)).1 le_rfl)

def flattenOrderHom
    {α : Type u} [OmegaCompletePartialOrder α] :
    OmegaScottPower (OmegaScottPower α) →o
      OmegaScottPower α where
  toFun := flattenRaw
  monotone' := flattenRaw_monotone

theorem flattenRaw_map_omegaSup
    {α : Type u} [OmegaCompletePartialOrder α]
    (chain :
      Chain (OmegaScottPower (OmegaScottPower α))) :
    flattenRaw (ωSup chain) =
      ωSup (chain.map flattenOrderHom) := by
  change
    flattenRaw (⨆ index, chain index) =
      ⨆ index, flattenRaw (chain index)
  exact
    (show
      GaloisConnection
        (flattenRaw :
          OmegaScottPower (OmegaScottPower α) →
            OmegaScottPower α)
        (principalRaw :
          OmegaScottPower α →
            OmegaScottPower (OmegaScottPower α))
      from fun family bound =>
        flattenRaw_le_iff family bound).l_iSup

def flatten
    {α : Type u} [OmegaCompletePartialOrder α] :
    omegaScottPowerCpo (OmegaScottPower α) ⟶
      omegaScottPowerCpo α where
  toFun := flattenRaw
  monotone' := flattenRaw_monotone
  map_ωSup' := flattenRaw_map_omegaSup

theorem flattenRaw_principal
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    flattenRaw (principalRaw values) = values := by
  apply le_antisymm
  · exact
      (flattenRaw_le_iff
        (principalRaw values) values).2 le_rfl
  · apply le_sSup
    apply
      (mem_memberSet_iff
        (α := α)
        (principalRaw
          (α := OmegaScottPower α) values)
        values).2
    change values ≤ values
    exact le_rfl

/-! ## Direct image for arbitrary omega-CPO morphisms -/

def mapRaw
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (values : OmegaScottPower α) :
    OmegaScottPower β :=
  TopologicalSpace.Closeds.closure
    (omegaScottLift function '' carrier values)

def preimage
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (values : OmegaScottPower β) :
    OmegaScottPower α :=
  values.preimage
    (continuousHom_omegaScott_continuous function)

theorem mapRaw_le_iff
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (values : OmegaScottPower α)
    (bound : OmegaScottPower β) :
    mapRaw function values ≤ bound ↔
      values ≤ preimage function bound := by
  change
    TopologicalSpace.Closeds.closure
        (omegaScottLift function '' carrier values) ≤
          bound ↔
      values ≤
        bound.preimage
          (continuousHom_omegaScott_continuous function)
  rw [TopologicalSpace.Closeds.closure_le]
  constructor
  · intro imageSubset source sourceMember
    exact imageSubset ⟨source, sourceMember, rfl⟩
  · rintro preimageSubset target
      ⟨source, sourceMember, rfl⟩
    exact preimageSubset sourceMember

theorem mapRaw_monotone
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β) :
    Monotone (mapRaw function) := by
  intro left right ordered
  apply
    (mapRaw_le_iff
      function left (mapRaw function right)).2
  exact le_trans ordered
    ((mapRaw_le_iff
      function right (mapRaw function right)).1 le_rfl)

def mapOrderHom
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β) :
    OmegaScottPower α →o OmegaScottPower β where
  toFun := mapRaw function
  monotone' := mapRaw_monotone function

theorem mapRaw_map_omegaSup
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (chain : Chain (OmegaScottPower α)) :
    mapRaw function (ωSup chain) =
      ωSup (chain.map (mapOrderHom function)) := by
  change
    mapRaw function (⨆ index, chain index) =
      ⨆ index, mapRaw function (chain index)
  exact
    (show
      GaloisConnection
        (mapRaw function :
          OmegaScottPower α → OmegaScottPower β)
        (preimage function)
      from fun values bound =>
        mapRaw_le_iff function values bound).l_iSup

def map
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β) :
    omegaScottPowerCpo α ⟶ omegaScottPowerCpo β where
  toFun := mapRaw function
  monotone' := mapRaw_monotone function
  map_ωSup' := mapRaw_map_omegaSup function

theorem mapRaw_id
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    mapRaw (ContinuousHom.id : α →𝒄 α) values =
      values := by
  apply TopologicalSpace.Closeds.ext
  change
    closure
        (id '' carrier values) =
      carrier values
  rw [image_id]
  change
    closure
        (↑values : Set (WithOmegaScott α)) =
      ↑values
  exact values.isClosed.closure_eq

theorem mapRaw_comp
    {α β γ : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    [OmegaCompletePartialOrder γ]
    (first : α →𝒄 β)
    (second : β →𝒄 γ)
    (values : OmegaScottPower α) :
    mapRaw second (mapRaw first values) =
      mapRaw (second.comp first) values := by
  apply TopologicalSpace.Closeds.ext
  apply Subset.antisymm
  · apply closure_minimal
    · rintro target ⟨middle, middleMember, rfl⟩
      have closedPreimage :
          IsClosed
            (omegaScottLift second ⁻¹'
              closure
                (omegaScottLift (second.comp first) ''
                  carrier values)) :=
        isClosed_closure.preimage
          (continuousHom_omegaScott_continuous second)
      apply
        (closure_minimal
          (s := omegaScottLift first '' carrier values)
          (t :=
            omegaScottLift second ⁻¹'
              closure
                (omegaScottLift (second.comp first) ''
                  carrier values))
          ?_ closedPreimage)
        middleMember
      rintro image ⟨source, sourceMember, rfl⟩
      exact
        subset_closure
          ⟨source, sourceMember, rfl⟩
    · exact isClosed_closure
  · apply closure_minimal
    · rintro target ⟨source, sourceMember, rfl⟩
      apply subset_closure
      exact
        ⟨omegaScottLift first source,
          subset_closure
            ⟨source, sourceMember, rfl⟩,
          rfl⟩
    · exact isClosed_closure

/-! ## The omega-CPO endofunctor -/

def powerObject
    (object : ωCPO.{u}) :
    ωCPO.{u} :=
  omegaScottPowerCpo object

def powerMap
    {source target : ωCPO.{u}}
    (morphism : source ⟶ target) :
    powerObject source ⟶ powerObject target :=
  map morphism

/--
Omega-Scott closed lower sets form a genuine endofunctor on all omega-CPOs
and continuous maps.
-/
def omegaScottPowerFunctor :
    ωCPO.{u} ⥤ ωCPO.{u} where
  obj := powerObject
  map := powerMap
  map_id object := by
    apply ContinuousHom.ext
    intro values
    exact mapRaw_id values
  map_comp first second := by
    apply ContinuousHom.ext
    intro values
    exact (mapRaw_comp first second values).symm

/-! ## Unit -/

theorem mapRaw_principal
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (value : α) :
    mapRaw function (principalRaw value) =
      principalRaw (function value) := by
  apply TopologicalSpace.Closeds.ext
  apply Subset.antisymm
  · apply closure_minimal
    · rintro target ⟨source, sourceLe, rfl⟩
      exact function.monotone sourceLe
    · exact isClosed_Iic _
  · intro target targetLe
    have topMember :
        WithOmegaScott.toOmegaScott (function value) ∈
          carrier
            (mapRaw function (principalRaw value)) :=
      subset_closure
        ⟨WithOmegaScott.toOmegaScott value,
          le_rfl, rfl⟩
    exact
      isLowerSet
        (mapRaw function (principalRaw value))
        targetLe topMember

def omegaScottPowerUnit :
    𝟭 ωCPO.{u} ⟶ omegaScottPowerFunctor where
  app object := principal
  naturality := by
    intro source target morphism
    apply ContinuousHom.ext
    intro value
    exact (mapRaw_principal morphism value).symm

/-! ## Multiplication and monad laws -/

theorem preimage_map_principal
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (bound : OmegaScottPower β) :
    preimage (map function) (principalRaw bound) =
      principalRaw (preimage function bound) := by
  apply TopologicalSpace.Closeds.ext
  ext values
  change
    mapRaw function
        (WithOmegaScott.ofOmegaScott values) ≤ bound ↔
      WithOmegaScott.ofOmegaScott values ≤
        preimage function bound
  exact
    mapRaw_le_iff function
      (WithOmegaScott.ofOmegaScott values) bound

theorem preimage_principal_principal
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    preimage (principal : α →𝒄 OmegaScottPower α)
        (principalRaw values) =
      values := by
  apply TopologicalSpace.Closeds.ext
  ext value
  change
    principalRaw (WithOmegaScott.ofOmegaScott value) ≤
        values ↔
      value ∈ carrier values
  constructor
  · intro principalSubset
    exact principalSubset le_rfl
  · intro valueMember target targetLe
    exact isLowerSet values targetLe valueMember

theorem preimage_flatten_principal
    {α : Type u} [OmegaCompletePartialOrder α]
    (bound : OmegaScottPower α) :
    preimage
        (flatten :
          OmegaScottPower (OmegaScottPower α) →𝒄
            OmegaScottPower α)
        (principalRaw bound) =
      principalRaw (principalRaw bound) := by
  apply TopologicalSpace.Closeds.ext
  ext family
  change
    flattenRaw (WithOmegaScott.ofOmegaScott family) ≤
        bound ↔
      WithOmegaScott.ofOmegaScott family ≤
        principalRaw bound
  exact
    flattenRaw_le_iff
      (WithOmegaScott.ofOmegaScott family) bound

theorem flattenRaw_mapRaw_natural
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (function : α →𝒄 β)
    (family :
      OmegaScottPower (OmegaScottPower α)) :
    flattenRaw (mapRaw (map function) family) =
      mapRaw function (flattenRaw family) := by
  apply eq_of_forall_ge_iff
  intro bound
  rw [flattenRaw_le_iff]
  rw [mapRaw_le_iff]
  rw [preimage_map_principal]
  rw [← flattenRaw_le_iff]
  rw [← mapRaw_le_iff]

theorem flattenRaw_mapRaw_principal
    {α : Type u} [OmegaCompletePartialOrder α]
    (values : OmegaScottPower α) :
    flattenRaw
        (mapRaw
          (principal : α →𝒄 OmegaScottPower α)
          values) =
      values := by
  apply eq_of_forall_ge_iff
  intro bound
  rw [flattenRaw_le_iff]
  rw [mapRaw_le_iff]
  rw [preimage_principal_principal]

theorem flattenRaw_assoc
    {α : Type u} [OmegaCompletePartialOrder α]
    (family :
      OmegaScottPower
        (OmegaScottPower (OmegaScottPower α))) :
    flattenRaw
        (mapRaw
          (flatten :
            OmegaScottPower (OmegaScottPower α) →𝒄
              OmegaScottPower α)
          family) =
      flattenRaw (flattenRaw family) := by
  apply eq_of_forall_ge_iff
  intro bound
  rw [flattenRaw_le_iff]
  rw [mapRaw_le_iff]
  rw [preimage_flatten_principal]
  exact
    (flattenRaw_le_iff
      family (principalRaw bound)).symm.trans
      (flattenRaw_le_iff
        (flattenRaw family) bound).symm

def omegaScottPowerMultiplication :
    omegaScottPowerFunctor ⋙ omegaScottPowerFunctor ⟶
      omegaScottPowerFunctor where
  app object := flatten
  naturality := by
    intro source target morphism
    apply ContinuousHom.ext
    intro family
    exact
      flattenRaw_mapRaw_natural morphism family

/--
The unseparated omega-Scott closed lower-set monad on all omega-CPOs.

This is a Hoare/lower closed-set monad.  It does not separate divergence from
empty deadlock and is not identified with the Abramsky powerdomain.
-/
def omegaScottPowerMonad :
    CategoryTheory.Monad ωCPO.{u} where
  toFunctor := omegaScottPowerFunctor
  η := omegaScottPowerUnit
  μ := omegaScottPowerMultiplication
  assoc object := by
    apply ContinuousHom.ext
    intro family
    exact flattenRaw_assoc family
  left_unit object := by
    apply ContinuousHom.ext
    intro values
    exact flattenRaw_principal values
  right_unit object := by
    apply ContinuousHom.ext
    intro values
    exact flattenRaw_mapRaw_principal values

end Cantilune.Pi.FMSCpoOmegaScottPower
