import Cantilune.Pi.FMSCpoConcreteBilimitExhaustivity

/-!
# The terminal coalgebra of the concrete FMS recursive domain

The concrete embedding--projection bilimit is not merely a fixed point.  This
module proves the final-sequence half of algebraic compactness for the actual
endofunctor

`ActualAgentFunctor = actionFunctor ⋙ pointwiseOmegaScottPowerFunctor`.

For an arbitrary coalgebra `c : X ⟶ F X`, its finite observations are defined
recursively:

* stage zero is the unique collapse to the singleton seed;
* stage `n+1` is `c ≫ F.map (stage n)`.

These observations form a cone over the concrete projection tower, hence have
a unique lift to its explicit inverse limit.  The lift is a genuine
`Coalgebra.Hom`.  Joint monicity of all finite projections proves uniqueness
among every coalgebra morphism, not only among canonical sources.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoEmbeddingProjectionBilimit

open CategoryTheory
open CategoryTheory.Endofunctor
open CategoryTheory.Limits
open OmegaCompletePartialOrder
open Cantilune.Pi.FMSModel
open Cantilune.Pi.FMSCpoActualDomainEquationBoundary

/-! ## Finite observations of an arbitrary coalgebra -/

/-- The final-sequence observations generated by an arbitrary coalgebra. -/
def concreteCoalgebraConeLeg
    (source : Coalgebra ActualAgentFunctor) :
    (n : Nat) → source.V ⟶ ConcreteActualIteration n
  | 0 => collapseWorldModel source.V
  | n + 1 =>
      source.str ≫
        ActualAgentFunctor.map (concreteCoalgebraConeLeg source n)

@[simp]
theorem concreteCoalgebraConeLeg_zero
    (source : Coalgebra ActualAgentFunctor) :
    concreteCoalgebraConeLeg source 0 =
      collapseWorldModel source.V :=
  rfl

@[simp]
theorem concreteCoalgebraConeLeg_succ
    (source : Coalgebra ActualAgentFunctor)
    (n : Nat) :
    concreteCoalgebraConeLeg source (n + 1) =
      source.str ≫
        ActualAgentFunctor.map (concreteCoalgebraConeLeg source n) :=
  rfl

/-- The recursively generated observations respect every tower projection. -/
theorem concreteCoalgebraConeLeg_compatible
    (source : Coalgebra ActualAgentFunctor)
    (n : Nat) :
    concreteCoalgebraConeLeg source (n + 1) ≫
        (concreteActualIterationPair n).projection =
      concreteCoalgebraConeLeg source n := by
  induction n with
  | zero =>
      apply NatTrans.ext
      funext world
      apply ContinuousHom.ext
      intro value
      rfl
  | succ n inductionHypothesis =>
      change
        (source.str ≫
            ActualAgentFunctor.map
              (concreteCoalgebraConeLeg source (n + 1))) ≫
              ActualAgentFunctor.map
                (concreteActualIterationPair n).projection =
          source.str ≫
            ActualAgentFunctor.map
              (concreteCoalgebraConeLeg source n)
      simp only [Category.assoc, ← ActualAgentFunctor.map_comp,
        inductionHypothesis]

/-- The arbitrary-coalgebra observations as a cone into the projection chain. -/
abbrev concreteCoalgebraCone
    (source : Coalgebra ActualAgentFunctor) :
    concreteModelProjectionChain.ContinuousCone source.V where
  leg := concreteCoalgebraConeLeg source
  compatible := concreteCoalgebraConeLeg_compatible source

/-- The unique underlying map from an arbitrary coalgebra into the limit. -/
def concreteCoalgebraToLimit
    (source : Coalgebra ActualAgentFunctor) :
    source.V ⟶ concreteIterationLimit :=
  (concreteCoalgebraCone source).lift

/-- The map into the limit has exactly the recursively prescribed observations. -/
@[simp]
theorem concreteCoalgebraToLimit_projection
    (source : Coalgebra ActualAgentFunctor)
    (n : Nat) :
    concreteCoalgebraToLimit source ≫
        concreteIterationLimitProjection n =
      concreteCoalgebraConeLeg source n :=
  (concreteCoalgebraCone source).lift_projection n

/-! ## The lift is a coalgebra morphism -/

/--
The explicit coalgebra on the concrete limit.  Keeping this spelling visible
avoids relying on reducibility of the nested fixed-point record while proving
its universal property.
-/
def concreteActualCoalgebra : Coalgebra ActualAgentFunctor where
  V := concreteIterationLimit
  str := concreteBilimitExhaustivity.unfold

/-- The explicit coalgebra is definitionally the fixed-point coalgebra. -/
theorem concreteActualCoalgebra_eq_fixedPoint :
    concreteActualCoalgebra =
      concreteActualFixedPointWitness.coalgebra :=
  rfl

/--
After folding, the coalgebra equation for the universal lift is determined by
all finite projections.
-/
theorem concreteCoalgebraToLimit_map_fold
    (source : Coalgebra ActualAgentFunctor) :
    source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source) ≫
        concreteIterationFold =
      concreteCoalgebraToLimit source := by
  apply concreteIterationLimitProjection_jointly_monic
  intro n
  cases n with
  | zero =>
      apply NatTrans.ext
      funext world
      apply ContinuousHom.ext
      intro value
      rfl
  | succ n =>
      simp only [Category.assoc]
      rw [concreteIterationFold_projection (n + 1)]
      change
        source.str ≫
            ActualAgentFunctor.map (concreteCoalgebraToLimit source) ≫
              ActualAgentFunctor.map
                (concreteIterationLimitProjection n) =
          concreteCoalgebraToLimit source ≫
            concreteIterationLimitProjection (n + 1)
      rw [← ActualAgentFunctor.map_comp]
      rw [concreteCoalgebraToLimit_projection]
      rw [concreteCoalgebraToLimit_projection]
      rfl

/-- The universal lift satisfies the native coalgebra-morphism square. -/
theorem concreteCoalgebraToLimit_hom_condition
    (source : Coalgebra ActualAgentFunctor) :
    source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source) =
      concreteCoalgebraToLimit source ≫
        concreteActualCoalgebra.str := by
  change
    source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source) =
      concreteCoalgebraToLimit source ≫
        concreteBilimitExhaustivity.unfold
  calc
    source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source) =
        (source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source)) ≫
          (concreteIterationFold ≫ concreteBilimitExhaustivity.unfold) := by
            rw [concreteBilimitExhaustivity.fold_unfold]
            rw [Category.comp_id]
    _ =
        (source.str ≫ ActualAgentFunctor.map (concreteCoalgebraToLimit source) ≫
          concreteIterationFold) ≫ concreteBilimitExhaustivity.unfold := by
            simp only [Category.assoc]
    _ =
        concreteCoalgebraToLimit source ≫
          concreteBilimitExhaustivity.unfold := by
            rw [concreteCoalgebraToLimit_map_fold]

/-- The universal map bundled as a genuine morphism in `Coalgebra F`. -/
def concreteCoalgebraToTerminal
    (source : Coalgebra ActualAgentFunctor) :
    source ⟶ concreteActualCoalgebra where
  f := concreteCoalgebraToLimit source
  h := concreteCoalgebraToLimit_hom_condition source

/-! ## Uniqueness and terminality -/

/--
The underlying model map of a coalgebra morphism into the explicit concrete
coalgebra, with the limit carrier exposed in its result type.
-/
def concreteCoalgebraHomUnderlying
    (source : Coalgebra ActualAgentFunctor)
    (candidate : source ⟶ concreteActualCoalgebra) :
    source.V ⟶ concreteIterationLimit :=
  candidate.f

@[simp]
theorem concreteCoalgebraToTerminal_underlying
    (source : Coalgebra ActualAgentFunctor) :
    concreteCoalgebraHomUnderlying source
        (concreteCoalgebraToTerminal source) =
      concreteCoalgebraToLimit source :=
  rfl

/--
Every coalgebra morphism into the concrete fixed point has the canonical
finite observation at every stage.
-/
theorem concreteCoalgebraHom_projection
    (source : Coalgebra ActualAgentFunctor)
    (candidate :
      source ⟶ concreteActualCoalgebra)
    (n : Nat) :
    concreteCoalgebraHomUnderlying source candidate ≫
        concreteIterationLimitProjection n =
      concreteCoalgebraConeLeg source n := by
  have candidateCondition :
      source.str ≫
          ActualAgentFunctor.map
            (concreteCoalgebraHomUnderlying source candidate) =
        concreteCoalgebraHomUnderlying source candidate ≫
          concreteBilimitExhaustivity.unfold := by
    exact candidate.h
  induction n with
  | zero =>
      apply NatTrans.ext
      funext world
      apply ContinuousHom.ext
      intro value
      rfl
  | succ n inductionHypothesis =>
      rw [← ConcreteIterationFoldInverse.unfold_foldConeLeg
        concreteBilimitExhaustivity.toFoldInverse (n + 1)]
      change
        (concreteCoalgebraHomUnderlying source candidate ≫
            concreteBilimitExhaustivity.unfold) ≫
              concreteFoldConeLeg (n + 1) =
          concreteCoalgebraConeLeg source (n + 1)
      rw [← candidateCondition]
      rw [Category.assoc]
      change
        source.str ≫
            ActualAgentFunctor.map
              (concreteCoalgebraHomUnderlying source candidate) ≫
              ActualAgentFunctor.map
                (concreteIterationLimitProjection n) =
          concreteCoalgebraConeLeg source (n + 1)
      rw [← ActualAgentFunctor.map_comp]
      rw [inductionHypothesis]
      rfl

/-- Every coalgebra morphism into the fixed point is the universal lift. -/
theorem concreteCoalgebraToTerminal_unique
    (source : Coalgebra ActualAgentFunctor)
    (candidate :
      source ⟶ concreteActualCoalgebra) :
    candidate = concreteCoalgebraToTerminal source := by
  apply Coalgebra.ext
  change
    concreteCoalgebraHomUnderlying source candidate =
      concreteCoalgebraHomUnderlying source
        (concreteCoalgebraToTerminal source)
  apply concreteIterationLimitProjection_jointly_monic
  intro n
  rw [concreteCoalgebraHom_projection source candidate n]
  rw [concreteCoalgebraToTerminal_underlying]
  exact concreteCoalgebraToLimit_projection source n |>.symm

/--
The concrete fixed point is terminal among all coalgebras of the actual
recursive endofunctor.
-/
def concreteActualCoalgebraIsTerminal :
    IsTerminal concreteActualCoalgebra :=
  IsTerminal.ofUniqueHom
    concreteCoalgebraToTerminal
    concreteCoalgebraToTerminal_unique

/--
The coalgebra induced by `concreteActualFixedPointWitness` is terminal among
all coalgebras of the actual recursive endofunctor.
-/
def concreteActualTerminalCoalgebra :
    IsTerminal concreteActualFixedPointWitness.coalgebra := by
  rw [← concreteActualCoalgebra_eq_fixedPoint]
  exact concreteActualCoalgebraIsTerminal

end Cantilune.Pi.FMSCpoEmbeddingProjectionBilimit
