import Cantilune.Pi.FMSCpoFiniteStrictPower

/-!
# A genuine finite Hoare powerdomain fragment in `ωCPO`

For a finite partial order `α`, the nonempty Hoare powerdomain consists of
nonempty lower subsets of `α`, ordered by inclusion.  Because `α` is finite,
every such lower set is finite and Scott closed, and every monotone operation
out of the carrier is omega-Scott-continuous.

This file constructs the actual omega-CPO together with continuous principal
embedding, lower direct image, union, and flattening.  It proves the functor,
choice, and two unit equations needed by the finite Hoare monad fragment.

The construction is deliberately local to finite bases.  It has neither an
empty deadlock element nor a separate divergence element, and it is not the
Abramsky powerdomain on all omega-CPOs.  In particular, nothing below supplies
algebraic compactness, an FMS agent-domain solution, adequacy, definability, or
full abstraction.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoFiniteHoarePower

open CategoryTheory
open OmegaCompletePartialOrder
open Cantilune.Pi.FMSCpoFiniteStrictPower

universe u

/-- A set is lower when it contains every smaller element of each member. -/
def IsLowerSet {α : Type u} [PartialOrder α] (values : Set α) : Prop :=
  ∀ ⦃upper lower : α⦄, upper ∈ values → lower ≤ upper → lower ∈ values

/-- Nonempty lower sets, ordered by inclusion. -/
abbrev HoarePower (α : Type u) [PartialOrder α] :=
  { values : Set α // values.Nonempty ∧ IsLowerSet values }

/-- The underlying set of a Hoare value. -/
def carrier {α : Type u} [PartialOrder α] :
    HoarePower α → Set α :=
  Subtype.val

@[simp]
theorem carrier_mk
    {α : Type u} [PartialOrder α]
    (values : Set α)
    (property : values.Nonempty ∧ IsLowerSet values) :
    carrier (⟨values, property⟩ : HoarePower α) = values :=
  rfl

/--
The supremum of an omega chain of nonempty lower sets is their union.  The
zeroth member witnesses nonemptiness, and lower closure is inherited from the
chain member containing the chosen upper element.
-/
noncomputable instance hoareOmegaCompletePartialOrder
    (α : Type u) [PartialOrder α] :
    OmegaCompletePartialOrder (HoarePower α) where
  ωSup chain :=
    ⟨⋃ index, carrier (chain index), by
      constructor
      · rcases (chain 0).property.1 with ⟨value, member⟩
        exact ⟨value, Set.mem_iUnion.2 ⟨0, member⟩⟩
      · intro upper lower upperMember lowerLe
        rcases Set.mem_iUnion.1 upperMember with ⟨index, member⟩
        exact Set.mem_iUnion.2
          ⟨index, (chain index).property.2 member lowerLe⟩⟩
  le_ωSup chain index value member :=
    Set.mem_iUnion.2 ⟨index, member⟩
  ωSup_le chain upper upperBound value member := by
    rcases Set.mem_iUnion.1 member with ⟨index, inIndex⟩
    exact upperBound index inIndex

/-- A finite base gives a finite Hoare carrier. -/
noncomputable instance hoareFinite
    (α : Type u) [PartialOrder α] [Finite α] :
    Finite (HoarePower α) := by
  infer_instance

/-- The finite Hoare carrier as an object of the actual mathlib `ωCPO`. -/
abbrev hoareCpo (α : Type u) [PartialOrder α] : ωCPO :=
  ωCPO.of (HoarePower α)

/-- The principal lower set generated by one element. -/
def principalRaw
    {α : Type u} [PartialOrder α] (value : α) :
    HoarePower α :=
  ⟨{ lower | lower ≤ value },
    ⟨⟨value, le_rfl⟩,
      by
        intro upper lower upperLe lowerLe
        exact le_trans lowerLe upperLe⟩⟩

@[simp]
theorem mem_principalRaw
    {α : Type u} [PartialOrder α] {lower value : α} :
    lower ∈ carrier (principalRaw value) ↔ lower ≤ value :=
  Iff.rfl

theorem principalRaw_monotone
    {α : Type u} [PartialOrder α] :
    Monotone (principalRaw : α → HoarePower α) := by
  intro left right ordered value member
  exact le_trans member ordered

/--
On a finite omega-CPO, the principal embedding is a genuine continuous map.
Finiteness is essential: principal ideals need not preserve omega suprema in
an arbitrary non-algebraic omega-CPO.
-/
def principal
    {α : Type u} [OmegaCompletePartialOrder α] [Finite α] :
    ωCPO.of α ⟶ hoareCpo α :=
  continuousOfFiniteMonotone principalRaw principalRaw_monotone

@[simp]
theorem principal_apply
    {α : Type u} [OmegaCompletePartialOrder α] [Finite α]
    (value : α) :
    principal value = principalRaw value :=
  rfl

/-- Binary Hoare choice is union of two nonempty lower sets. -/
def choiceRaw
    {α : Type u} [PartialOrder α] :
    HoarePower α × HoarePower α → HoarePower α
  | ⟨left, right⟩ =>
      ⟨carrier left ∪ carrier right, by
        constructor
        · rcases left.property.1 with ⟨value, member⟩
          exact ⟨value, Or.inl member⟩
        · intro upper lower member lowerLe
          rcases member with inLeft | inRight
          · exact Or.inl (left.property.2 inLeft lowerLe)
          · exact Or.inr (right.property.2 inRight lowerLe)⟩

theorem choiceRaw_monotone
    {α : Type u} [PartialOrder α] :
    Monotone (choiceRaw : HoarePower α × HoarePower α → HoarePower α) := by
  rintro ⟨left₁, right₁⟩ ⟨left₂, right₂⟩ ordered value member
  rcases ordered with ⟨leftOrder, rightOrder⟩
  rcases member with inLeft | inRight
  · exact Or.inl (leftOrder inLeft)
  · exact Or.inr (rightOrder inRight)

/-- Hoare choice as an actual continuous map for finite bases. -/
def choice
    {α : Type u} [PartialOrder α] [Finite α] :
    ωCPO.of (HoarePower α × HoarePower α) ⟶ hoareCpo α :=
  continuousOfFiniteMonotone choiceRaw choiceRaw_monotone

theorem choice_assoc
    {α : Type u} [PartialOrder α] [Finite α]
    (left middle right : HoarePower α) :
    choice (choice (left, middle), right) =
      choice (left, choice (middle, right)) := by
  change
    choiceRaw (choiceRaw (left, middle), right) =
      choiceRaw (left, choiceRaw (middle, right))
  apply Subtype.ext
  ext value
  simp [choiceRaw, or_assoc]

theorem choice_comm
    {α : Type u} [PartialOrder α] [Finite α]
    (left right : HoarePower α) :
    choice (left, right) = choice (right, left) := by
  change choiceRaw (left, right) = choiceRaw (right, left)
  apply Subtype.ext
  ext value
  simp [choiceRaw, or_comm]

theorem choice_idem
    {α : Type u} [PartialOrder α] [Finite α]
    (value : HoarePower α) :
    choice (value, value) = value := by
  change choiceRaw (value, value) = value
  apply Subtype.ext
  change carrier value ∪ carrier value = carrier value
  exact Set.union_self (carrier value)

/--
Lower direct image of a monotone function.  Taking downward closure after
direct image is the order-sensitive Hoare action; plain direct image would
not in general be a lower set.
-/
def mapRaw
    {α β : Type u}
    [PartialOrder α] [PartialOrder β]
    (function : α → β) (_monotone : Monotone function)
    (values : HoarePower α) :
    HoarePower β :=
  ⟨{ target | ∃ source ∈ carrier values, target ≤ function source }, by
    constructor
    · rcases values.property.1 with ⟨source, member⟩
      exact ⟨function source, source, member, le_rfl⟩
    · intro upper lower
      rintro ⟨source, sourceMember, upperLe⟩ lowerLe
      exact ⟨source, sourceMember, le_trans lowerLe upperLe⟩⟩

theorem mapRaw_monotone
    {α β : Type u}
    [PartialOrder α] [PartialOrder β]
    (function : α → β) (monotone : Monotone function) :
    Monotone (mapRaw function monotone : HoarePower α → HoarePower β) := by
  intro left right subset target
  rintro ⟨source, sourceMember, targetLe⟩
  exact ⟨source, subset sourceMember, targetLe⟩

/-- Lower direct image as a continuous map for finite source bases. -/
def map
    {α β : Type u}
    [PartialOrder α] [PartialOrder β] [Finite α]
    (function : α → β) (monotone : Monotone function) :
    hoareCpo α ⟶ hoareCpo β :=
  continuousOfFiniteMonotone
    (mapRaw function monotone)
    (mapRaw_monotone function monotone)

theorem mapRaw_principal
    {α β : Type u}
    [PartialOrder α] [PartialOrder β]
    (function : α → β) (monotone : Monotone function)
    (value : α) :
    mapRaw function monotone (principalRaw value) =
      principalRaw (function value) := by
  apply Subtype.ext
  ext target
  constructor
  · rintro ⟨source, sourceLe, targetLe⟩
    exact le_trans targetLe (monotone sourceLe)
  · intro targetLe
    exact ⟨value, le_rfl, targetLe⟩

theorem map_id
    {α : Type u} [PartialOrder α] [Finite α] :
    map (id : α → α) monotone_id =
      𝟙 (hoareCpo α) := by
  apply ContinuousHom.ext
  intro values
  apply Subtype.ext
  ext target
  constructor
  · rintro ⟨source, sourceMember, targetLe⟩
    exact values.property.2 sourceMember targetLe
  · intro targetMember
    exact ⟨target, targetMember, le_rfl⟩

theorem map_comp
    {α β γ : Type u}
    [PartialOrder α] [PartialOrder β] [PartialOrder γ]
    [Finite α] [Finite β]
    (first : α → β) (second : β → γ)
    (firstMonotone : Monotone first)
    (secondMonotone : Monotone second) :
    map first firstMonotone ≫ map second secondMonotone =
      map (second ∘ first) (secondMonotone.comp firstMonotone) := by
  apply ContinuousHom.ext
  intro values
  apply Subtype.ext
  ext target
  constructor
  · rintro ⟨middle, ⟨source, sourceMember, middleLe⟩, targetLe⟩
    exact
      ⟨source, sourceMember,
        le_trans targetLe (secondMonotone middleLe)⟩
  · rintro ⟨source, sourceMember, targetLe⟩
    exact
      ⟨first source,
        ⟨source, sourceMember, le_rfl⟩,
        targetLe⟩

theorem map_principal
    {α β : Type u}
    [OmegaCompletePartialOrder α] [PartialOrder β]
    [Finite α]
    (function : α → β) (monotone : Monotone function) :
    principal ≫ map function monotone =
      continuousOfFiniteMonotone
        (fun value => principalRaw (function value))
        (principalRaw_monotone.comp monotone) := by
  apply ContinuousHom.ext
  intro value
  exact mapRaw_principal function monotone value

/-- Union of every lower set in a nonempty lower family. -/
def flattenRaw
    {α : Type u} [PartialOrder α] :
    HoarePower (HoarePower α) → HoarePower α
  | family =>
      ⟨{ value | ∃ member ∈ carrier family, value ∈ carrier member }, by
        constructor
        · rcases family.property.1 with ⟨member, memberInFamily⟩
          rcases member.property.1 with ⟨value, valueInMember⟩
          exact ⟨value, member, memberInFamily, valueInMember⟩
        · intro upper lower
          rintro ⟨member, memberInFamily, upperInMember⟩ lowerLe
          exact
            ⟨member, memberInFamily,
              member.property.2 upperInMember lowerLe⟩⟩

theorem flattenRaw_monotone
    {α : Type u} [PartialOrder α] :
    Monotone (flattenRaw : HoarePower (HoarePower α) → HoarePower α) := by
  intro left right subset value
  rintro ⟨member, memberInLeft, valueInMember⟩
  exact ⟨member, subset memberInLeft, valueInMember⟩

/-- Hoare multiplication is continuous on finite bases. -/
def flatten
    {α : Type u} [PartialOrder α] [Finite α] :
    hoareCpo (HoarePower α) ⟶ hoareCpo α :=
  continuousOfFiniteMonotone flattenRaw flattenRaw_monotone

/-- Flattening the principal lower family returns the original lower set. -/
theorem flatten_principal
    {α : Type u} [PartialOrder α] [Finite α]
    (values : HoarePower α) :
    flatten (principalRaw values) = values := by
  apply Subtype.ext
  ext value
  constructor
  · rintro ⟨member, memberSubset, valueMember⟩
    exact memberSubset valueMember
  · intro valueMember
    exact
      ⟨values,
        (mem_principalRaw (lower := values) (value := values)).2 le_rfl,
        valueMember⟩

/--
Mapping the principal embedding over a Hoare value and then flattening is the
second unit equation of the finite Hoare monad fragment.
-/
theorem flatten_mapRaw_principal
    {α : Type u} [PartialOrder α] [Finite α]
    (values : HoarePower α) :
    flatten
        (mapRaw principalRaw principalRaw_monotone values) =
      values := by
  apply Subtype.ext
  ext value
  constructor
  · rintro ⟨member, ⟨generator, generatorMember, memberSubset⟩,
      valueMember⟩
    exact
      values.property.2 generatorMember
        (memberSubset valueMember)
  · intro valueMember
    exact
      ⟨principalRaw value,
        ⟨value, valueMember, le_rfl⟩,
        le_rfl⟩

/--
The finite Hoare carrier has genuine non-discrete order whenever the base has
a strict comparison: principal lower sets reflect that comparison.
-/
theorem principal_strict
    {α : Type u} [PartialOrder α] [Finite α]
    {lower upper : α} (ordered : lower < upper) :
    principalRaw lower < principalRaw upper := by
  constructor
  · exact principalRaw_monotone ordered.le
  · intro reverse
    have upperLeLower : upper ≤ lower :=
      reverse (show upper ∈ carrier (principalRaw upper) from le_rfl)
    exact (not_le_of_gt ordered) upperLeLower

end Cantilune.Pi.FMSCpoFiniteHoarePower
