import Cantilune.Pi.FMSCpoNondeterministicSolutionSet

/-!
# The free nondeterministic omega-CPO on one discrete generator

The nullary construction supplies the free `NDωCPO` object on the empty
source.  This file gives the first nonempty source without assuming the
global solution-set condition.

The four carrier points remember independently whether a finite expression
contains divergence and whether it contains the single generator.  Deadlock
is the empty expression.  The order is the least one forced by divergence
being least and choice being monotone:

```text
        generator       deadlock
            ↑              ↑
  divergence + generator   |
            ↑              |
         divergence --------
```

In particular deadlock is not below the generator.  This is exactly the
order relation that invalidated the raw strict-powerset candidate.

The resulting structured arrow is proved initial.  Hence it gives a genuine
singleton solution set at the equality-ordered one-point omega-CPO.  It does
not construct the all-source solution-set condition: arbitrary sources
still require closure under countable suprema together with a small
cardinality family of representatives.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoNondeterministicUnary

open CategoryTheory
open CategoryTheory.Limits
open OmegaCompletePartialOrder
open Cantilune.Pi.FMSExternalPackage
open Cantilune.Pi.FMSCpoFinitePower
open Cantilune.Pi.FMSCpoFiniteStrictPower
open Cantilune.Pi.FMSCpoNondeterministicCategory

namespace Unary

/-! ## The four-point carrier -/

/--
A term records the possible occurrence of divergence and of the unique
generator.  The absent/absent point is deadlock.
-/
@[ext]
structure Carrier where
  hasDivergence : Bool
  hasGenerator : Bool
deriving DecidableEq, Fintype

/--
The order generated by:

* divergence is below every term;
* choice is monotone; and
* the generator and deadlock have no imposed comparison.
-/
def Carrier.le (left right : Carrier) : Prop :=
  if left.hasDivergence then
    left.hasGenerator ≤ right.hasGenerator
  else
    left = right

instance : LE Carrier := ⟨Carrier.le⟩

instance : PartialOrder Carrier where
  le_refl value := by
    change Carrier.le value value
    rcases value with ⟨divergent, generatorPresent⟩
    cases divergent <;> simp [Carrier.le]
  le_trans first second third firstSecond secondThird := by
    change Carrier.le first second at firstSecond
    change Carrier.le second third at secondThird
    change Carrier.le first third
    rcases first with ⟨firstDivergent, firstGenerator⟩
    rcases second with ⟨secondDivergent, secondGenerator⟩
    rcases third with ⟨thirdDivergent, thirdGenerator⟩
    cases firstDivergent <;>
      cases firstGenerator <;>
      cases secondDivergent <;>
      cases secondGenerator <;>
      cases thirdDivergent <;>
      cases thirdGenerator <;>
      simp_all [Carrier.le]
  le_antisymm left right leftRight rightLeft := by
    change Carrier.le left right at leftRight
    change Carrier.le right left at rightLeft
    rcases left with ⟨leftDivergent, leftGenerator⟩
    rcases right with ⟨rightDivergent, rightGenerator⟩
    cases leftDivergent <;>
      cases leftGenerator <;>
      cases rightDivergent <;>
      cases rightGenerator <;>
      simp_all [Carrier.le]
    all_goals
      exact
        False.elim
          ((by decide : ¬ (true : Bool) ≤ false)
            (by assumption))

/-- Every increasing sequence in the finite carrier has a greatest member. -/
theorem chain_has_greatest_member
    (chain : Chain Carrier) :
    ∃ index, ∀ other, chain other ≤ chain index := by
  obtain ⟨maximum, ⟨index, rfl⟩, maximal⟩ :=
    (Set.toFinite (Set.range chain)).exists_maximal
      (Set.range_nonempty chain)
  refine ⟨index, ?_⟩
  intro other
  rcases le_total other index with before | after
  · exact chain.monotone before
  · exact maximal ⟨other, rfl⟩ (chain.monotone after)

/-- The selected greatest member of a finite-carrier omega chain. -/
noncomputable def chainGreatestIndex
    (chain : Chain Carrier) :
    ℕ :=
  Classical.choose (chain_has_greatest_member chain)

theorem chain_le_greatest
    (chain : Chain Carrier)
    (index : ℕ) :
    chain index ≤ chain (chainGreatestIndex chain) :=
  Classical.choose_spec (chain_has_greatest_member chain) index

noncomputable instance : OmegaCompletePartialOrder Carrier where
  ωSup chain := chain (chainGreatestIndex chain)
  le_ωSup := chain_le_greatest
  ωSup_le chain _value upper :=
    upper (chainGreatestIndex chain)

/-- Order-theoretic divergence. -/
def divergence : Carrier := ⟨true, false⟩

/-- Semilattice identity, distinct from divergence. -/
def deadlock : Carrier := ⟨false, false⟩

/-- The unique generator. -/
def generator : Carrier := ⟨false, true⟩

/-- Choice is union of the two occurrence bits. -/
def choiceRaw (pair : Carrier × Carrier) : Carrier :=
  ⟨pair.1.hasDivergence || pair.2.hasDivergence,
    pair.1.hasGenerator || pair.2.hasGenerator⟩

theorem choiceRaw_monotone : Monotone choiceRaw := by
  rintro
    ⟨⟨leftDivergent, leftGenerator⟩,
      ⟨rightDivergent, rightGenerator⟩⟩
    ⟨⟨leftDivergent', leftGenerator'⟩,
      ⟨rightDivergent', rightGenerator'⟩⟩
    ordered
  change
    Carrier.le
      ⟨leftDivergent, leftGenerator⟩
      ⟨leftDivergent', leftGenerator'⟩ ∧
    Carrier.le
      ⟨rightDivergent, rightGenerator⟩
      ⟨rightDivergent', rightGenerator'⟩
    at ordered
  change
    Carrier.le
      (choiceRaw
        (⟨leftDivergent, leftGenerator⟩,
          ⟨rightDivergent, rightGenerator⟩))
      (choiceRaw
        (⟨leftDivergent', leftGenerator'⟩,
          ⟨rightDivergent', rightGenerator'⟩))
  cases leftDivergent <;>
    cases leftGenerator <;>
    cases rightDivergent <;>
    cases rightGenerator <;>
    cases leftDivergent' <;>
    cases leftGenerator' <;>
    cases rightDivergent' <;>
    cases rightGenerator' <;>
    simp_all [Carrier.le, choiceRaw]

/-- Choice as a genuine continuous operation. -/
abbrev choice : ωCPO.of (Carrier × Carrier) ⟶ ωCPO.of Carrier :=
  continuousOfFiniteMonotone choiceRaw choiceRaw_monotone

@[simp]
theorem choice_apply (left right : Carrier) :
    choice (left, right) = choiceRaw (left, right) :=
  continuousOfFiniteMonotone_apply
    choiceRaw choiceRaw_monotone (left, right)

theorem divergence_le (value : Carrier) : divergence ≤ value := by
  change Carrier.le divergence value
  rcases value with ⟨divergent, generatorPresent⟩
  cases divergent <;> cases generatorPresent <;>
    simp [divergence, Carrier.le]

theorem choice_assoc (left middle right : Carrier) :
    choice (choice (left, middle), right) =
      choice (left, choice (middle, right)) := by
  change
    choiceRaw (choiceRaw (left, middle), right) =
      choiceRaw (left, choiceRaw (middle, right))
  apply Carrier.ext <;> simp [choiceRaw, Bool.or_assoc]

theorem choice_comm (left right : Carrier) :
    choice (left, right) = choice (right, left) := by
  change choiceRaw (left, right) = choiceRaw (right, left)
  apply Carrier.ext <;> simp [choiceRaw, Bool.or_comm]

theorem choice_idem (value : Carrier) :
    choice (value, value) = value := by
  rw [choice_apply]
  rcases value with ⟨divergent, generatorPresent⟩
  simp [choiceRaw]

theorem deadlock_choice (value : Carrier) :
    choice (deadlock, value) = value := by
  rw [choice_apply]
  rcases value with ⟨divergent, generatorPresent⟩
  simp [choiceRaw, deadlock]

theorem divergence_ne_deadlock : divergence ≠ deadlock := by
  decide

/-- The actual four-point nondeterministic computation. -/
abbrev computation : NondeterministicComputation where
  carrier := ωCPO.of Carrier
  divergence := divergence
  divergence_le := divergence_le
  deadlock := deadlock
  choice := choice
  choice_assoc := choice_assoc
  choice_comm := choice_comm
  choice_idem := choice_idem
  deadlock_choice := deadlock_choice

/-- The free candidate, later proved genuinely free. -/
abbrev object : NDωCPO where
  computation := computation

/-! ## Evaluation in an arbitrary target -/

/-- Select an algebra element when a bit is present and deadlock otherwise. -/
def component
    (target : NDωCPO)
    (present : Bool)
    (value : target.carrier) :
    target.carrier :=
  if present then value else target.computation.deadlock

theorem target_choice_deadlock
    (target : NDωCPO)
    (value : target.carrier) :
    target.computation.choice
        (value, target.computation.deadlock) =
      value := by
  rw [target.computation.choice_comm]
  exact target.computation.deadlock_choice value

theorem component_or
    (target : NDωCPO)
    (left right : Bool)
    (value : target.carrier) :
    component target (left || right) value =
      target.computation.choice
        (component target left value,
          component target right value) := by
  cases left <;> cases right
  · exact (target.computation.deadlock_choice _).symm
  · exact (target.computation.deadlock_choice _).symm
  · exact (target_choice_deadlock target _).symm
  · exact (target.computation.choice_idem _).symm

theorem target_choice_interchange
    (target : NDωCPO)
    (a b c d : target.carrier) :
    target.computation.choice
        (target.computation.choice (a, b),
          target.computation.choice (c, d)) =
      target.computation.choice
        (target.computation.choice (a, c),
          target.computation.choice (b, d)) := by
  calc
    target.computation.choice
        (target.computation.choice (a, b),
          target.computation.choice (c, d)) =
        target.computation.choice
          (a, target.computation.choice
            (b, target.computation.choice (c, d))) := by
      rw [target.computation.choice_assoc]
    _ =
        target.computation.choice
          (a, target.computation.choice
            (c, target.computation.choice (b, d))) := by
      congr 1
      rw [← target.computation.choice_assoc,
        target.computation.choice_comm b c,
        target.computation.choice_assoc]
    _ =
        target.computation.choice
          (target.computation.choice (a, c),
            target.computation.choice (b, d)) := by
      rw [target.computation.choice_assoc]

/-- Interpret a four-point term under a chosen target generator. -/
def evaluationRaw
    (target : NDωCPO)
    (targetGenerator : target.carrier)
    (term : Carrier) :
    target.carrier :=
  target.computation.choice
    (component target term.hasDivergence
      target.computation.divergence,
      component target term.hasGenerator targetGenerator)

theorem evaluationRaw_monotone
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    Monotone (evaluationRaw target targetGenerator) := by
  rintro ⟨leftDivergent, leftGenerator⟩
    ⟨rightDivergent, rightGenerator⟩ ordered
  change
    Carrier.le
      ⟨leftDivergent, leftGenerator⟩
      ⟨rightDivergent, rightGenerator⟩
    at ordered
  cases leftDivergent
  ·
    have equality :
        (⟨false, leftGenerator⟩ : Carrier) =
          ⟨rightDivergent, rightGenerator⟩ := by
      simpa [Carrier.le] using ordered
    cases equality
    exact le_rfl
  ·
    cases leftGenerator
    ·
      change
        target.computation.choice
            (target.computation.divergence,
              target.computation.deadlock) ≤
          evaluationRaw target targetGenerator
            ⟨rightDivergent, rightGenerator⟩
      rw [target_choice_deadlock]
      exact target.computation.divergence_le _
    ·
      have rightGeneratorPresent : rightGenerator = true := by
        cases rightGenerator
        ·
          exact
            False.elim
              ((by decide : ¬ (true : Bool) ≤ false)
                (by simpa [Carrier.le] using ordered))
        · rfl
      subst rightGenerator
      cases rightDivergent
      ·
        change
          target.computation.choice
              (target.computation.divergence,
                targetGenerator) ≤
            target.computation.choice
              (target.computation.deadlock,
                targetGenerator)
        apply target.computation.choice.monotone
        exact
          ⟨target.computation.divergence_le
              target.computation.deadlock,
            le_rfl⟩
      · exact le_rfl

/-- Evaluation is continuous because the source carrier is finite. -/
abbrev evaluation
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    ωCPO.of Carrier ⟶ target.carrier :=
  continuousOfFiniteMonotone
    (evaluationRaw target targetGenerator)
    (evaluationRaw_monotone target targetGenerator)

@[simp]
theorem evaluation_apply
    (target : NDωCPO)
    (targetGenerator : target.carrier)
    (term : Carrier) :
    evaluation target targetGenerator term =
      evaluationRaw target targetGenerator term :=
  continuousOfFiniteMonotone_apply
    (evaluationRaw target targetGenerator)
    (evaluationRaw_monotone target targetGenerator)
    term

theorem evaluation_divergence
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    evaluation target targetGenerator divergence =
      target.computation.divergence := by
  rw [evaluation_apply]
  change
    target.computation.choice
        (target.computation.divergence,
          target.computation.deadlock) =
      target.computation.divergence
  exact target_choice_deadlock target _

theorem evaluation_deadlock
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    evaluation target targetGenerator deadlock =
      target.computation.deadlock := by
  rw [evaluation_apply]
  change
    target.computation.choice
        (target.computation.deadlock,
          target.computation.deadlock) =
      target.computation.deadlock
  exact target.computation.choice_idem _

theorem evaluation_generator
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    evaluation target targetGenerator generator =
      targetGenerator := by
  rw [evaluation_apply]
  change
    target.computation.choice
        (target.computation.deadlock, targetGenerator) =
      targetGenerator
  exact target.computation.deadlock_choice _

theorem evaluation_choice
    (target : NDωCPO)
    (targetGenerator : target.carrier)
    (left right : Carrier) :
    evaluation target targetGenerator (choice (left, right)) =
      target.computation.choice
        (evaluation target targetGenerator left,
          evaluation target targetGenerator right) := by
  rw [choice_apply, evaluation_apply, evaluation_apply, evaluation_apply]
  change
    target.computation.choice
      (component target
          (left.hasDivergence || right.hasDivergence)
          target.computation.divergence,
        component target
          (left.hasGenerator || right.hasGenerator)
          targetGenerator) =
      target.computation.choice
        (target.computation.choice
          (component target left.hasDivergence
              target.computation.divergence,
            component target left.hasGenerator targetGenerator),
          target.computation.choice
            (component target right.hasDivergence
                target.computation.divergence,
              component target right.hasGenerator targetGenerator))
  rw [component_or, component_or]
  exact target_choice_interchange target _ _ _ _

/-- The unique strict continuous semilattice evaluation arrow. -/
def toTarget
    (target : NDωCPO)
    (targetGenerator : target.carrier) :
    object ⟶ target where
  hom := evaluation target targetGenerator
  map_divergence := evaluation_divergence target targetGenerator
  map_deadlock := evaluation_deadlock target targetGenerator
  map_choice := evaluation_choice target targetGenerator

/-! ## The one-generator universal property -/

/-- The equality-ordered one-point source. -/
abbrev source : ωCPO :=
  ωCPO.of (EqualityOrder Unit)

/-- The generator selecting the non-divergent generator point. -/
def sourceGenerator :
    source ⟶ NDωCPO.forget.obj object :=
  EqualityOrder.continuousTo (fun _ : Unit => generator)

/-- The one-generator structured arrow. -/
def universalArrow :
    StructuredArrow source NDωCPO.forget :=
  StructuredArrow.mk sourceGenerator

/-- Evaluate into the codomain of an arbitrary structured arrow. -/
def universalTo
    (target : StructuredArrow source NDωCPO.forget) :
    universalArrow ⟶ target :=
  StructuredArrow.homMk
    (toTarget target.right (target.hom ()))
    (by
      apply ContinuousHom.ext
      intro value
      rcases value with ⟨⟩
      exact evaluation_generator target.right (target.hom ()))

/-- Every strict arrow is determined by its value at the unique generator. -/
theorem toTarget_unique
    (target : NDωCPO)
    (targetGenerator : target.carrier)
    (morphism : object ⟶ target)
    (mapsGenerator : morphism.hom generator = targetGenerator) :
    morphism = toTarget target targetGenerator := by
  apply NDωCPO.Hom.ext
  apply ContinuousHom.ext
  intro term
  change
    (ConcreteCategory.hom (C := ωCPO) morphism.hom) term =
      (ConcreteCategory.hom (C := ωCPO)
        (evaluation target targetGenerator)) term
  rcases term with ⟨divergent, generatorPresent⟩
  cases divergent <;> cases generatorPresent
  ·
    change
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) deadlock =
        (ConcreteCategory.hom (C := ωCPO)
          (evaluation target targetGenerator)) deadlock
    calc
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) deadlock =
          target.computation.deadlock :=
        morphism.map_deadlock
      _ =
          (ConcreteCategory.hom (C := ωCPO)
            (evaluation target targetGenerator)) deadlock :=
        (evaluation_deadlock target targetGenerator).symm
  ·
    change
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) generator =
        (ConcreteCategory.hom (C := ωCPO)
          (evaluation target targetGenerator)) generator
    calc
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) generator =
          targetGenerator :=
        mapsGenerator
      _ =
          (ConcreteCategory.hom (C := ωCPO)
            (evaluation target targetGenerator)) generator :=
        (evaluation_generator target targetGenerator).symm
  ·
    change
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) divergence =
        (ConcreteCategory.hom (C := ωCPO)
          (evaluation target targetGenerator)) divergence
    calc
      (ConcreteCategory.hom (C := ωCPO) morphism.hom) divergence =
          target.computation.divergence :=
        morphism.map_divergence
      _ =
          (ConcreteCategory.hom (C := ωCPO)
            (evaluation target targetGenerator)) divergence :=
        (evaluation_divergence target targetGenerator).symm
  ·
    change
      (ConcreteCategory.hom (C := ωCPO) morphism.hom)
          (choice (divergence, generator)) =
        (ConcreteCategory.hom (C := ωCPO)
          (evaluation target targetGenerator))
          (choice (divergence, generator))
    have evaluatedChoice :=
      evaluation_choice target targetGenerator
        divergence generator
    rw [evaluation_divergence, evaluation_generator]
      at evaluatedChoice
    calc
      (ConcreteCategory.hom (C := ωCPO) morphism.hom)
          (choice (divergence, generator)) =
          target.computation.choice
            ((ConcreteCategory.hom (C := ωCPO) morphism.hom)
                divergence,
              (ConcreteCategory.hom (C := ωCPO) morphism.hom)
                generator) :=
        morphism.map_choice divergence generator
      _ =
          target.computation.choice
            (target.computation.divergence, targetGenerator) := by
        rw [morphism.map_divergence, mapsGenerator]
      _ =
          (ConcreteCategory.hom (C := ωCPO)
            (evaluation target targetGenerator))
            (choice (divergence, generator)) :=
        evaluatedChoice.symm

/-- The one-generator structured arrow is genuinely initial. -/
def universalIsInitial :
    IsInitial universalArrow :=
  IsInitial.ofUniqueHom
    universalTo
    (by
      intro target morphism
      apply StructuredArrow.hom_ext
      apply toTarget_unique
      have triangle := StructuredArrow.w morphism
      exact
        congrArg
          (fun map => map ())
          triangle)

/--
The singleton family represented by `object` is a genuine local solution set
at the nonempty equality-ordered one-point source.
-/
theorem source_solutionSet :
    ∃ (ι : Type) (objects : ι → NDωCPO)
        (generators :
          ∀ index : ι,
            source ⟶ NDωCPO.forget.obj (objects index)),
      ∀ (target : NDωCPO)
        (targetGenerator : source ⟶ NDωCPO.forget.obj target),
        ∃ (index : ι) (factor : objects index ⟶ target),
          generators index ≫ NDωCPO.forget.map factor =
            targetGenerator := by
  refine
    ⟨PUnit, fun _ => object, fun _ => sourceGenerator, ?_⟩
  intro target targetGenerator
  refine
    ⟨PUnit.unit, toTarget target (targetGenerator ()), ?_⟩
  apply ContinuousHom.ext
  intro value
  rcases value with ⟨⟩
  exact evaluation_generator target (targetGenerator ())

end Unary

end Cantilune.Pi.FMSCpoNondeterministicUnary
