import Cantilune.Pi.FMSCpoSupportedActualAgent
import Cantilune.Pi.PowerdomainUnseparated.Fubini

/-!
# Genuine supported parallel and restriction coalgebra

`FMSCpoSupportedActualAgent.supportedHeadLayer` deliberately maps parallel
and restriction to bottom.  This independent module constructs the stronger
finite-control coalgebra without changing that conservative base module.

Parallel is generated by:

* left and right native interleaving;
* lower-omega-Scott Fubini pairing of both head computations; and
* the genuine free-input/free-output synchronization kernel.

Restriction is generated by a syntax-level Table-4 fold.  It classifies the
last name of the extended world, blocks actions on the restricted subject,
extrudes a restricted output value as bound output, swaps nested fresh names,
and retains tau.  The fold is then extended over the lower powerdomain by
`mapRaw` followed by `flattenRaw`.

The resulting layers have actual one-step folds in the concrete recursive
FMS agent.  Restriction additionally uses the independently constructed
recursive terminal-coalgebra operator.  The conservative source coalgebra
still maps a nested parallel or restriction head to bottom, so this file also
gives a kernel-checked counterexample to treating its one-step parallel fold
as a recursively complete Table-5 interpretation.  It does not claim a
recursive Table-5 parallel operator or Agent-observation full abstraction.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoSupportedParallelRestriction

universe u

open CategoryTheory
open CategoryTheory.Endofunctor
open OmegaCompletePartialOrder
open Cantilune.Pi
open Cantilune.Pi.FMSModel
open Cantilune.Pi.FMSContext
open Cantilune.Pi.FMSCpoContext
open Cantilune.Pi.FMSBinderInstantiation
open Cantilune.Pi.FMSCanonicalHidingSyntax
open Cantilune.Pi.FMSOperationalSyntaxBridge
open Cantilune.Pi.FMSCpoActionFunctor
open Cantilune.Pi.FMSCpoFinitePower
open Cantilune.Pi.FMSCpoNameAbstractionFunctor
open Cantilune.Pi.FMSCpoOmegaScottPower
open Cantilune.Pi.FMSCpoOmegaScottStrength
open Cantilune.Pi.FMSCpoActualDomainEquationBoundary
open Cantilune.Pi.FMSCpoEmbeddingProjectionBilimit
open Cantilune.Pi.FMSCpoAgentRestriction
open Cantilune.Pi.FMSCpoAgentOperationalBridge
open Cantilune.Pi.FMSCpoNominalDeltaCoherence
open Cantilune.Pi.FMSCpoSupportedActualAgent
open Cantilune.Pi.FMSCpoUnseparatedSourceCore
open Cantilune.Pi.PowerdomainUnseparated

/-! ## Continuous syntax continuation maps -/

/-- Put a fixed supported process on the right of a continuation. -/
def parallelRightContinuation
    (world : World) (right : SupportedProc world 0) :
    processCpoModel.obj world →𝒄 processCpoModel.obj world :=
  EqualityOrder.continuousTo fun left => .parallel left right

/-- Put a fixed supported process on the left of a continuation. -/
def parallelLeftContinuation
    (world : World) (left : SupportedProc world 0) :
    processCpoModel.obj world →𝒄 processCpoModel.obj world :=
  EqualityOrder.continuousTo fun right => .parallel left right

/-- Weaken a closed supported process into the successor world. -/
def weakenProcess
    (world : World) :
    processCpoModel.obj world →𝒄 processCpoModel.obj (world + 1) :=
  EqualityOrder.continuousTo fun process =>
    SupportedProc.renameFree Fin.castSucc process

/-- Left interleaving on known input continuations. -/
def parallelRightKnown
    (world : World) (right : SupportedProc world 0) :
    (Fin world → processCpoModel.obj world) →𝒄
      (Fin world → processCpoModel.obj world) :=
  ContinuousHom.ofFun
    (fun known name =>
      parallelRightContinuation world right (known name))
    (by fun_prop)

/-- Left interleaving on a complete input abstraction. -/
def parallelRightAbstraction
    (world : World) (right : SupportedProc world 0) :
    NameAbstractionCarrier processCpoModel world →𝒄
      NameAbstractionCarrier processCpoModel world :=
  FMSCpoActionFunctor.productMap
    (parallelRightKnown world right)
    (parallelRightContinuation (world + 1)
      (SupportedProc.renameFree Fin.castSucc right))

/-- Right interleaving on known input continuations. -/
def parallelLeftKnown
    (world : World) (left : SupportedProc world 0) :
    (Fin world → processCpoModel.obj world) →𝒄
      (Fin world → processCpoModel.obj world) :=
  ContinuousHom.ofFun
    (fun known name =>
      parallelLeftContinuation world left (known name))
    (by fun_prop)

/-- Right interleaving on a complete input abstraction. -/
def parallelLeftAbstraction
    (world : World) (left : SupportedProc world 0) :
    NameAbstractionCarrier processCpoModel world →𝒄
      NameAbstractionCarrier processCpoModel world :=
  FMSCpoActionFunctor.productMap
    (parallelLeftKnown world left)
    (parallelLeftContinuation (world + 1)
      (SupportedProc.renameFree Fin.castSucc left))

/-! ## Action-level interleaving -/

/-- Transform every continuation of a left action by parallel on the right. -/
def interleaveLeftAction
    (world : World) (right : SupportedProc world 0) :
    ActionRepresentation processCpoModel world →𝒄
      ActionRepresentation processCpoModel world :=
  separatedCases
    (taggedContinuous fun channel =>
      separatedInl.comp
        (ContinuousHom.ofFun
          (fun abstraction =>
            (nameTag channel,
              parallelRightAbstraction world right abstraction))
          (by fun_prop)))
    (separatedCases
      (doubleTaggedContinuous fun channel value =>
        (separatedInr.comp separatedInl).comp
          (ContinuousHom.ofFun
            (fun continuation =>
              ((nameTag channel, nameTag value),
                parallelRightContinuation world right continuation))
            (by fun_prop)))
      (separatedCases
        (taggedContinuous fun channel =>
          (separatedInr.comp (separatedInr.comp separatedInl)).comp
            (ContinuousHom.ofFun
              (fun continuation =>
                (nameTag channel,
                  parallelRightContinuation (world + 1)
                    (SupportedProc.renameFree Fin.castSucc right)
                    continuation))
              (by fun_prop)))
        ((separatedInr.comp (separatedInr.comp separatedInr)).comp
          (parallelRightContinuation world right))))

/-- Transform every continuation of a right action by parallel on the left. -/
def interleaveRightAction
    (world : World) (left : SupportedProc world 0) :
    ActionRepresentation processCpoModel world →𝒄
      ActionRepresentation processCpoModel world :=
  separatedCases
    (taggedContinuous fun channel =>
      separatedInl.comp
        (ContinuousHom.ofFun
          (fun abstraction =>
            (nameTag channel,
              parallelLeftAbstraction world left abstraction))
          (by fun_prop)))
    (separatedCases
      (doubleTaggedContinuous fun channel value =>
        (separatedInr.comp separatedInl).comp
          (ContinuousHom.ofFun
            (fun continuation =>
              ((nameTag channel, nameTag value),
                parallelLeftContinuation world left continuation))
            (by fun_prop)))
      (separatedCases
        (taggedContinuous fun channel =>
          (separatedInr.comp (separatedInr.comp separatedInl)).comp
            (ContinuousHom.ofFun
              (fun continuation =>
                (nameTag channel,
                  parallelLeftContinuation (world + 1)
                    (SupportedProc.renameFree Fin.castSucc left)
                    continuation))
              (by fun_prop)))
        ((separatedInr.comp (separatedInr.comp separatedInr)).comp
          (parallelLeftContinuation world left))))

/-! ## Flat action space and the genuine free synchronization kernel -/

/--
Every function out of a flat omega-CPO is continuous.  This local lemma is
used only after proving that the complete supported action representation is
flat; it does not equip the lower powerdomain itself with a discrete order.
-/
def continuousOfFlat
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (flat : ∀ {left right : α}, left ≤ right → left = right)
    (function : α → β) :
    α →𝒄 β where
  toFun := function
  monotone' := by
    intro left right ordered
    rw [flat ordered]
  map_ωSup' := by
    intro chain
    have sourceSup : ωSup chain = chain 0 := by
      apply le_antisymm
      · apply ωSup_le
        intro index
        have same :
            chain 0 = chain index :=
          flat (chain.monotone (Nat.zero_le index))
        simpa [same]
      · exact le_ωSup chain 0
    rw [sourceSup]
    apply le_antisymm
    · exact le_ωSup (chain.map
        { toFun := function
          monotone' := by
            intro left right ordered
            rw [flat ordered] }) 0
    · apply ωSup_le
      intro index
      have same :
          chain 0 = chain index :=
        flat (chain.monotone (Nat.zero_le index))
      simpa [same]

private theorem equalityOrder_le_eq
    {α : Type u} {left right : EqualityOrder α}
    (ordered : left ≤ right) :
    left = right :=
  ordered

private theorem function_le_eq
    {ι α : Type u}
    [OmegaCompletePartialOrder α]
    (flat : ∀ {left right : α}, left ≤ right → left = right)
    {left right : ι → α}
    (ordered : left ≤ right) :
    left = right := by
  funext index
  exact flat (ordered index)

private theorem product_le_eq
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (leftFlat : ∀ {left right : α}, left ≤ right → left = right)
    (rightFlat : ∀ {left right : β}, left ≤ right → left = right)
    {left right : α × β}
    (ordered : left ≤ right) :
    left = right := by
  exact Prod.ext
    (leftFlat ordered.1)
    (rightFlat ordered.2)

private theorem sum_le_eq
    {α β : Type u}
    [OmegaCompletePartialOrder α]
    [OmegaCompletePartialOrder β]
    (leftFlat : ∀ {left right : α}, left ≤ right → left = right)
    (rightFlat : ∀ {left right : β}, left ≤ right → left = right)
    {left right : α ⊕ β}
    (ordered : left ≤ right) :
    left = right := by
  cases left with
  | inl left =>
      cases right with
      | inl right =>
          exact congrArg Sum.inl
            (leftFlat (Sum.inl_le_inl_iff.1 ordered))
      | inr right =>
          exact (Sum.not_inl_le_inr ordered).elim
  | inr left =>
      cases right with
      | inl right =>
          exact (Sum.not_inr_le_inl ordered).elim
      | inr right =>
          exact congrArg Sum.inr
            (rightFlat (Sum.inr_le_inr_iff.1 ordered))

private theorem process_le_eq
    {world : World}
    {left right : processCpoModel.obj world}
    (ordered : left ≤ right) :
    left = right :=
  equalityOrder_le_eq ordered

private theorem abstraction_le_eq
    {world : World}
    {left right : NameAbstractionCarrier processCpoModel world}
    (ordered : left ≤ right) :
    left = right :=
  product_le_eq
    (function_le_eq process_le_eq)
    process_le_eq ordered

/-- The complete supported action carrier is flat. -/
theorem action_le_eq
    {world : World}
    {left right : ActionRepresentation processCpoModel world}
    (ordered : left ≤ right) :
    left = right :=
  sum_le_eq
    (product_le_eq equalityOrder_le_eq abstraction_le_eq)
    (sum_le_eq
      (product_le_eq
        (product_le_eq equalityOrder_le_eq equalityOrder_le_eq)
        process_le_eq)
      (sum_le_eq
        (product_le_eq equalityOrder_le_eq process_le_eq)
        process_le_eq))
    ordered

/-- Pairs of supported actions are flat as well. -/
theorem actionPair_le_eq
    {world : World}
    {left right :
      ActionRepresentation processCpoModel world ×
        ActionRepresentation processCpoModel world}
    (ordered : left ≤ right) :
    left = right :=
  product_le_eq action_le_eq action_le_eq ordered

/--
One genuine free input/output synchronization.

All non-complementary cells and channel mismatches return lower-power bottom.
Bound-output synchronization is intentionally left to the restriction layer,
where the exported name and its scope are available.
-/
def syncPairRaw
    (world : World)
    (pair :
      ActionRepresentation processCpoModel world ×
        ActionRepresentation processCpoModel world) :
    OmegaScottPower (ActionRepresentation processCpoModel world) :=
  match pair.1, pair.2 with
  | Sum.inl (inputChannel, (known, _fresh)),
      Sum.inr (Sum.inl ((outputChannel, value), continuation)) =>
      if tagName inputChannel = tagName outputChannel then
        principalRaw
          (syntaxTauAction world
            (.parallel (known (tagName value)) continuation))
      else ⊥
  | Sum.inr (Sum.inl ((outputChannel, value), continuation)),
      Sum.inl (inputChannel, (known, _fresh)) =>
      if tagName inputChannel = tagName outputChannel then
        principalRaw
          (syntaxTauAction world
            (.parallel continuation (known (tagName value))))
      else ⊥
  | _, _ => ⊥

/-- The free synchronization matrix as an actual continuous action kernel. -/
def syncPairStep
    (world : World) :
    (ActionRepresentation processCpoModel world ×
      ActionRepresentation processCpoModel world) →𝒄
        OmegaScottPower
          (ActionRepresentation processCpoModel world) :=
  continuousOfFlat actionPair_le_eq (syncPairRaw world)

/--
Fubini pairs both computations, the synchronization kernel maps every pair,
and monad multiplication joins the generated lower-power computations.
-/
def synchronizationLayer
    (world : World)
    (left right :
      OmegaScottPower
        (ActionRepresentation processCpoModel world)) :
    OmegaScottPower
      (ActionRepresentation processCpoModel world) :=
  flattenRaw
    (mapRaw (syncPairStep world)
      (PowerdomainUnseparated.fubiniRaw left right))

/-- A matching principal input/output pair produces a principal tau action. -/
theorem synchronization_principal_input_output
    (world : World)
    (channel value : Fin world)
    (known : Fin world → processCpoModel.obj world)
    (fresh : processCpoModel.obj (world + 1))
    (continuation : processCpoModel.obj world) :
    synchronizationLayer world
        (principalRaw
          (Sum.inl
            (nameTag channel, (known, fresh))))
        (principalRaw
          (Sum.inr
            (Sum.inl
              ((nameTag channel, nameTag value),
                continuation)))) =
      principalRaw
        (syntaxTauAction world
          (.parallel (known value) continuation)) := by
  unfold synchronizationLayer
  rw [PowerdomainUnseparated.fubiniRaw_principal]
  rw [mapRaw_principal]
  rw [flattenRaw_principal]
  simp [syncPairStep, syncPairRaw, continuousOfFlat]

/-- The mirror principal output/input pair produces the mirror tau target. -/
theorem synchronization_principal_output_input
    (world : World)
    (channel value : Fin world)
    (continuation : processCpoModel.obj world)
    (known : Fin world → processCpoModel.obj world)
    (fresh : processCpoModel.obj (world + 1)) :
    synchronizationLayer world
        (principalRaw
          (Sum.inr
            (Sum.inl
              ((nameTag channel, nameTag value),
                continuation))))
        (principalRaw
          (Sum.inl
            (nameTag channel, (known, fresh)))) =
      principalRaw
        (syntaxTauAction world
          (.parallel continuation (known value))) := by
  unfold synchronizationLayer
  rw [PowerdomainUnseparated.fubiniRaw_principal]
  rw [mapRaw_principal]
  rw [flattenRaw_principal]
  simp [syncPairStep, syncPairRaw, continuousOfFlat]

/-- Prefix-shaped mirror synchronization, stated directly on supported syntax. -/
theorem synchronization_syntax_output_input
    (world : World)
    (channel value : Fin world)
    (continuation : SupportedProc world 0)
    (body : SupportedProc world 1) :
    synchronizationLayer world
        (principalRaw
          (syntaxFreeOutputAction world channel value continuation))
        (principalRaw
          (syntaxInputAction world channel body)) =
      principalRaw
        (syntaxTauAction world
          (.parallel continuation
            (SupportedProc.instantiateOuter value body))) := by
  unfold synchronizationLayer
  rw [PowerdomainUnseparated.fubiniRaw_principal]
  rw [mapRaw_principal]
  rw [flattenRaw_principal]
  simp [syncPairStep, syncPairRaw, continuousOfFlat,
    syntaxFreeOutputAction, syntaxInputAction]

/-! ## Syntax-level Table-4 restriction -/

/-- Hide the last free name in a supported continuation. -/
def restrictLastContinuation
    (world : World) :
    processCpoModel.obj (world + 1) →𝒄
      processCpoModel.obj world :=
  EqualityOrder.continuousTo
    FMSCanonicalHidingSyntax.SupportedProc.restrictLast

/--
Exchange the restricted name with a newer bound-output/input name and then
hide the (new) last coordinate.
-/
def swapThenRestrictContinuation
    (world : World) :
    processCpoModel.obj ((world + 1) + 1) →𝒄
      processCpoModel.obj (world + 1) :=
  EqualityOrder.continuousTo fun process =>
    FMSCanonicalHidingSyntax.SupportedProc.restrictLast
      (SupportedProc.renameFree
        (homToFun (lastTwoSwap world)) process)

/-- Restrict the last coordinate in every old-name input continuation. -/
def restrictKnownContinuation
    (world : World) :
    (Fin (world + 1) → processCpoModel.obj (world + 1)) →𝒄
      (Fin world → processCpoModel.obj world) :=
  ContinuousHom.ofFun
    (fun known old =>
      restrictLastContinuation world
        (known (Fin.castSucc old)))
    (by fun_prop)

/--
The complete supported Table-4 action transform.

The target is again the supported syntax carrier, so recursive restriction
is represented by `restrictLast` directly in each continuation.
-/
def syntaxRestrictionRaw
    (world : World)
    (action :
      ActionRepresentation processCpoModel (world + 1)) :
    OmegaScottPower
      (ActionRepresentation processCpoModel world) :=
  match action with
  | Sum.inl (channel, (known, fresh)) =>
      match oldName? world (tagName channel) with
      | none => ⊥
      | some oldChannel =>
          principalRaw
            (Sum.inl
              (nameTag oldChannel,
                (restrictKnownContinuation world known,
                  swapThenRestrictContinuation world fresh)))
  | Sum.inr (Sum.inl ((channel, value), continuation)) =>
      match oldName? world (tagName channel),
          oldName? world (tagName value) with
      | none, _ => ⊥
      | some oldChannel, none =>
          principalRaw
            (Sum.inr
              (Sum.inr
                (Sum.inl
                  (nameTag oldChannel, continuation))))
      | some oldChannel, some oldValue =>
          principalRaw
            (Sum.inr
              (Sum.inl
                ((nameTag oldChannel, nameTag oldValue),
                  FMSCanonicalHidingSyntax.SupportedProc.restrictLast
                    continuation)))
  | Sum.inr (Sum.inr (Sum.inl (channel, continuation))) =>
      match oldName? world (tagName channel) with
      | none => ⊥
      | some oldChannel =>
          principalRaw
            (Sum.inr
              (Sum.inr
                (Sum.inl
                  (nameTag oldChannel,
                    swapThenRestrictContinuation world continuation))))
  | Sum.inr (Sum.inr (Sum.inr continuation)) =>
      principalRaw
        (syntaxTauAction world
          (FMSCanonicalHidingSyntax.SupportedProc.restrictLast
            continuation))

/-- Table-4 action translation is continuous on the flat supported action. -/
def syntaxRestrictionStep
    (world : World) :
    ActionRepresentation processCpoModel (world + 1) →𝒄
      OmegaScottPower
        (ActionRepresentation processCpoModel world) :=
  continuousOfFlat action_le_eq (syntaxRestrictionRaw world)

/-- Kleisli extension of the syntax-level restriction transform. -/
def restrictionLayer
    (world : World)
    (values :
      OmegaScottPower
        (ActionRepresentation processCpoModel (world + 1))) :
    OmegaScottPower
      (ActionRepresentation processCpoModel world) :=
  flattenRaw
    (mapRaw (syntaxRestrictionStep world) values)

/-- Exact bound-output action over the supported syntax carrier. -/
def syntaxBoundOutputAction
    (world : World) (channel : Fin world)
    (continuation : processCpoModel.obj (world + 1)) :
    ActionRepresentation processCpoModel world :=
  Sum.inr
    (Sum.inr
      (Sum.inl (nameTag channel, continuation)))

/-- Tau under restriction remains tau with an explicitly restricted target. -/
theorem restriction_principal_tau
    (world : World)
    (continuation : processCpoModel.obj (world + 1)) :
    restrictionLayer world
        (principalRaw
          (syntaxTauAction (world + 1) continuation)) =
      principalRaw
        (syntaxTauAction world
          (FMSCanonicalHidingSyntax.SupportedProc.restrictLast
            continuation)) := by
  unfold restrictionLayer
  rw [mapRaw_principal, flattenRaw_principal]
  rfl

/-- A visible old-name free output survives restriction. -/
theorem restriction_principal_visible_output
    (world : World)
    (channel value : Fin world)
    (continuation : processCpoModel.obj (world + 1)) :
    restrictionLayer world
        (principalRaw
          (syntaxFreeOutputAction (world + 1)
            (Fin.castSucc channel) (Fin.castSucc value)
            continuation)) =
      principalRaw
        (syntaxFreeOutputAction world channel value
          (FMSCanonicalHidingSyntax.SupportedProc.restrictLast
            continuation)) := by
  unfold restrictionLayer
  rw [mapRaw_principal, flattenRaw_principal]
  simp [syntaxRestrictionStep, syntaxRestrictionRaw,
    syntaxFreeOutputAction, continuousOfFlat, oldName?,
    restrictLastContinuation]

/-- Output of the restricted value is a genuine bound-output action. -/
theorem restriction_principal_extrusion
    (world : World)
    (channel : Fin world)
    (continuation : processCpoModel.obj (world + 1)) :
    restrictionLayer world
        (principalRaw
          (syntaxFreeOutputAction (world + 1)
            (Fin.castSucc channel) (Fin.last world)
            continuation)) =
      principalRaw
        (syntaxBoundOutputAction world channel continuation) := by
  unfold restrictionLayer
  rw [mapRaw_principal, flattenRaw_principal]
  simp [syntaxRestrictionStep, syntaxRestrictionRaw,
    syntaxFreeOutputAction, syntaxBoundOutputAction,
    continuousOfFlat, oldName?]

/-! ## Genuine composite layers and their actual-Agent folds -/

/--
One complete parallel head over supported syntax.

The three joins are left interleaving, right interleaving, and Fubini
synchronization.  Unlike the conservative base layer, this is not bottom on
parallel prefixes.
-/
def supportedParallelLayer
    (world : World)
    (left right : SupportedProc world 0) :
    OmegaScottPower
      (ActionRepresentation processCpoModel world) :=
  (mapRaw (interleaveLeftAction world right)
      (supportedHeadLayer world left) ⊔
    mapRaw (interleaveRightAction world left)
      (supportedHeadLayer world right)) ⊔
    synchronizationLayer world
      (supportedHeadLayer world left)
      (supportedHeadLayer world right)

/-- One complete restriction head over canonically freshened syntax. -/
def supportedRestrictionLayer
    (world : World)
    (body : SupportedProc world 1) :
    OmegaScottPower
      (ActionRepresentation processCpoModel world) :=
  restrictionLayer world
    (supportedHeadLayer (world + 1)
      (SupportedProc.freshenOuter body))

/-- Map a supported action computation into the actual recursive Agent. -/
def mapSupportedLayerToAgent
    (world : World)
    (layer :
      OmegaScottPower
        (ActionRepresentation processCpoModel world)) :
    OmegaScottPower
      (ActionRepresentation Agent world) :=
  mapRaw
    (actionModelMapComponent supportedDenote world)
    layer

/-- Fold a genuine supported parallel head into the actual recursive Agent. -/
def supportedParallelAgent
    (world : World)
    (left right : SupportedProc world 0) :
    Agent.obj world :=
  agentFold.app world
    (mapSupportedLayerToAgent world
      (supportedParallelLayer world left right))

/-- Fold a genuine supported restriction head into the actual recursive Agent. -/
def supportedRestrictionOneStepAgent
    (world : World)
    (body : SupportedProc world 1) :
    Agent.obj world :=
  agentFold.app world
    (mapSupportedLayerToAgent world
      (supportedRestrictionLayer world body))

/-- The parallel fold/unfold square commutes exactly. -/
theorem supportedParallelAgent_unfold
    (world : World)
    (left right : SupportedProc world 0) :
    agentUnfold.app world
        (supportedParallelAgent world left right) =
      mapSupportedLayerToAgent world
        (supportedParallelLayer world left right) := by
  exact
    concreteActualAlgebraicCompactnessWitness.fixed.fold_unfold
      world
      (mapSupportedLayerToAgent world
        (supportedParallelLayer world left right))

/-- The restriction fold/unfold square commutes exactly. -/
theorem supportedRestrictionOneStepAgent_unfold
    (world : World)
    (body : SupportedProc world 1) :
    agentUnfold.app world
        (supportedRestrictionOneStepAgent world body) =
      mapSupportedLayerToAgent world
        (supportedRestrictionLayer world body) := by
  exact
    concreteActualAlgebraicCompactnessWitness.fixed.fold_unfold
      world
      (mapSupportedLayerToAgent world
        (supportedRestrictionLayer world body))

/--
The independently constructed recursive `agentRestriction` supplies the
full terminal-coalgebra restriction equation for every supported body.
-/
theorem supportedRecursiveRestriction_coalgebra_commutes
    (world : World)
    (body : SupportedProc world 1) :
    agentUnfold.app world
        (supportedRestrictionDenote world body) =
      (ActualAgentFunctor.map agentRestriction).app world
        (actionRestrictionKleisli world
          (agentUnfold.app (world + 1)
            (supportedDenote.app (world + 1)
              (SupportedProc.freshenOuter body)))) := by
  exact agentRestriction_unfold_at world _

/-- Recursive restriction of a supported tau is the actual Agent tau. -/
theorem supportedRecursiveRestriction_tau
    (world : World)
    (next : SupportedProc world 1) :
    supportedRestrictionDenote world (.tau next) =
      fixedTauAgent world
        (supportedRestrictionDenote world next) := by
  apply supportedRestriction_tau
  rw [show
    SupportedProc.freshenOuter (.tau next) =
      .tau (SupportedProc.freshenOuter next) by
        simp [SupportedProc.freshenOuter, SupportedProc.renameFree,
          SupportedProc.substituteBinderWith]]
  exact
    supportedDenote_tau (world + 1)
      (SupportedProc.freshenOuter next)

/-! ## Kernel boundary for the conservative source coalgebra -/

/--
The existing one-step construction loses an output nested below another
parallel because the conservative `supportedHeadLayer` maps that inner
parallel head to bottom.
-/
theorem nested_parallel_one_step_layer_is_bottom
    (world : World)
    (channel value : Fin world) :
    supportedParallelLayer world
        (.parallel
          (.output (.free channel) (.free value) .zero)
          .zero)
        .zero =
      (⊥ : OmegaScottPower
        (ActionRepresentation processCpoModel world)) := by
  simp [supportedParallelLayer, supportedHeadLayer,
    synchronizationLayer, mapRaw_bot,
    fubiniRaw_effectBottom_left,
    flattenRaw_effectBottom]

/-- Nevertheless, the nested output is a genuine native strong late-pi step. -/
theorem nested_parallel_left_output_native
    (world : World)
    (channel value : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.parallel
          (.parallel
            (.output (.free channel) (.free value) .zero)
            .zero)
          .zero))
      (.output channel.val value.val)
      (SupportedProc.reifyAtWorld
        ((.parallel
          (.parallel .zero .zero)
          .zero) : SupportedProc world 0)) := by
  have inner :=
    Late.NativeStep.parLeft
      (right := Raw.Proc.zero)
      (by simp [Raw.Action.boundNames])
      (output_reification_native world
        (.free channel) (.free value) .zero)
  have outer :=
    Late.NativeStep.parLeft
      (right := Raw.Proc.zero)
      (by simp [Raw.Action.boundNames])
      inner
  simpa [SupportedProc.reifyAtWorld, SupportedProc.reify] using outer

/--
Completeness claim for precisely the nested family above.  It is deliberately
small: refuting even this family is enough to refute recursive completeness
of the conservative one-step fold.
-/
def ConservativeOneStepNestedComplete : Prop :=
  ∀ (world : World) (channel value : Fin world),
    Late.NativeStep
        (SupportedProc.reifyAtWorld
          (.parallel
            (.parallel
              (.output (.free channel) (.free value) .zero)
              .zero)
            .zero))
        (.output channel.val value.val)
        (SupportedProc.reifyAtWorld
          ((.parallel
            (.parallel .zero .zero)
            .zero) : SupportedProc world 0)) →
      supportedParallelLayer world
          (.parallel
            (.output (.free channel) (.free value) .zero)
            .zero)
          .zero ≠
        (⊥ : OmegaScottPower
          (ActionRepresentation processCpoModel world))

/--
Kernel no-go: the conservative one-step fold cannot be advertised as a
recursively complete parallel semantics.  This refutes this construction,
not the existence of a richer mutually recursive Table-5 coalgebra.
-/
theorem no_conservative_one_step_nested_completeness :
    ¬ ConservativeOneStepNestedComplete := by
  intro complete
  unfold ConservativeOneStepNestedComplete at complete
  have nonBottom :=
    complete 1 (0 : Fin 1) (0 : Fin 1)
      (nested_parallel_left_output_native 1
        (0 : Fin 1) (0 : Fin 1))
  exact nonBottom
    (nested_parallel_one_step_layer_is_bottom 1
      (0 : Fin 1) (0 : Fin 1))

/-! ## Exact canonical layer equations -/

@[simp]
theorem freshenOuter_tau
    (next : SupportedProc world 1) :
    SupportedProc.freshenOuter (.tau next) =
      .tau (SupportedProc.freshenOuter next) :=
  by
    simp [SupportedProc.freshenOuter, SupportedProc.renameFree,
      SupportedProc.substituteBinderWith]

@[simp]
theorem freshenOuter_output_free
    (channel value : Fin world)
    (next : SupportedProc world 1) :
    SupportedProc.freshenOuter
        (.output (.free channel) (.free value) next) =
      .output (.free (Fin.castSucc channel))
        (.free (Fin.castSucc value))
        (SupportedProc.freshenOuter next) :=
  by
    simp [SupportedProc.freshenOuter, SupportedProc.renameFree,
      SupportedProc.substituteBinderWith,
      ScopedName.substituteBinder]

@[simp]
theorem freshenOuter_output_bound
    (channel : Fin world)
    (next : SupportedProc world 1) :
    SupportedProc.freshenOuter
        (.output (.free channel) (.bound (Fin.last 0)) next) =
      .output (.free (Fin.castSucc channel))
        (.free (Fin.last world))
        (SupportedProc.freshenOuter next) :=
  by
    simp [SupportedProc.freshenOuter, SupportedProc.renameFree,
      SupportedProc.substituteBinderWith,
      ScopedName.substituteBinder]

/-- A canonical output/input parallel contains both interleavings and tau. -/
theorem canonical_parallel_output_input_layer
    (world : World)
    (channel value : Fin world) :
    supportedParallelLayer world
        (.output (.free channel) (.free value) .zero)
        (.input (.free channel) .zero) =
      (principalRaw
          (interleaveLeftAction world
            (.input (.free channel) .zero)
            (syntaxFreeOutputAction world channel value .zero)) ⊔
        principalRaw
          (interleaveRightAction world
            (.output (.free channel) (.free value) .zero)
            (syntaxInputAction world channel .zero))) ⊔
        principalRaw
          (syntaxTauAction world
            (.parallel .zero .zero)) := by
  unfold supportedParallelLayer
  simp only [supportedHeadLayer, closedName_free]
  rw [mapRaw_principal, mapRaw_principal]
  rw [synchronization_syntax_output_input]
  simp [SupportedProc.instantiateOuter,
    SupportedProc.substituteBinderWith]

/-- A tau under supported restriction has the true restricted derivative. -/
theorem canonical_restriction_tau_layer
    (world : World)
    (next : SupportedProc world 1) :
    supportedRestrictionLayer world (.tau next) =
      principalRaw
        (syntaxTauAction world (.restrict next)) := by
  unfold supportedRestrictionLayer
  rw [freshenOuter_tau]
  rw [supportedHeadLayer]
  change
    restrictionLayer world
        (principalRaw
          (syntaxTauAction (world + 1)
            (SupportedProc.freshenOuter next))) =
      _
  rw [restriction_principal_tau]
  rw [SupportedProc.restrictLast_freshenOuter]

/-- An old-name output remains visible below supported restriction. -/
theorem canonical_restriction_visible_output_layer
    (world : World)
    (channel value : Fin world)
    (next : SupportedProc world 1) :
    supportedRestrictionLayer world
        (.output (.free channel) (.free value) next) =
      principalRaw
        (syntaxFreeOutputAction world channel value
          (.restrict next)) := by
  unfold supportedRestrictionLayer
  rw [freshenOuter_output_free]
  rw [supportedHeadLayer]
  change
    restrictionLayer world
        (principalRaw
          (syntaxFreeOutputAction (world + 1)
            (Fin.castSucc channel) (Fin.castSucc value)
            (SupportedProc.freshenOuter next))) =
      _
  rw [restriction_principal_visible_output]
  rw [SupportedProc.restrictLast_freshenOuter]

/-- Output of the locally restricted binder is a true bound output. -/
theorem canonical_restriction_extrusion_layer
    (world : World)
    (channel : Fin world)
    (next : SupportedProc world 1) :
    supportedRestrictionLayer world
        (.output (.free channel) (.bound (Fin.last 0)) next) =
      principalRaw
        (syntaxBoundOutputAction world channel
          (SupportedProc.freshenOuter next)) := by
  unfold supportedRestrictionLayer
  rw [freshenOuter_output_bound]
  rw [supportedHeadLayer]
  change
    restrictionLayer world
        (principalRaw
          (syntaxFreeOutputAction (world + 1)
            (Fin.castSucc channel) (Fin.last world)
            (SupportedProc.freshenOuter next))) =
      _
  exact restriction_principal_extrusion
    world channel (SupportedProc.freshenOuter next)

/-! ## Genuine standard late-pi representatives -/

/-- The canonical output/input parallel exposes the left output natively. -/
theorem canonical_parallel_left_interleaving_native
    (world : World)
    (channel value : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.parallel
          (.output (.free channel) (.free value) .zero)
          (.input (.free channel) .zero)))
      (.output channel.val value.val)
      (SupportedProc.reifyAtWorld
        (.parallel .zero
          (.input (.free channel) .zero))) := by
  apply Late.NativeStep.parLeft
  · simp [Raw.Action.boundNames]
  · exact output_reification_native world
      (.free channel) (.free value) .zero

/-- The same parallel exposes the right input with a genuinely fresh binder. -/
theorem canonical_parallel_right_interleaving_native
    (world : World)
    (channel value : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.parallel
          (.output (.free channel) (.free value) .zero)
          (.input (.free channel) .zero)))
      (.input channel.val world)
      (SupportedProc.reifyAtWorld
        (.parallel
          (.output (.free channel) (.free value) .zero)
          .zero)) := by
  apply Late.NativeStep.parRight
  · apply Finset.disjoint_singleton_left.mpr
    have channelFresh : world ≠ channel.val :=
      (ne_of_lt channel.isLt).symm
    have valueFresh : world ≠ value.val :=
      (ne_of_lt value.isLt).symm
    simp [SupportedProc.reify, ScopedName.reify,
      Raw.Proc.freeNames, channelFresh, valueFresh]
  · exact input_reification_native world (.free channel) .zero

/-- The complementary prefixes perform one genuine strong tau synchronization. -/
theorem canonical_parallel_sync_native
    (world : World)
    (channel value : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.parallel
          (.output (.free channel) (.free value) .zero)
          (.input (.free channel) .zero)))
      .tau
      (SupportedProc.reifyAtWorld
        ((.parallel .zero .zero) :
          SupportedProc world 0)) := by
  have step :=
    Late.NativeStep.syncLeft
      (output_reification_native world
        (.free channel) (.free value) .zero)
      (input_reification_native world (.free channel) .zero)
      (by
        simp [SupportedProc.reifyAtWorld, SupportedProc.reify,
          Raw.Proc.freeNames])
  simpa [SupportedProc.reifyAtWorld, SupportedProc.reify,
    inputReificationTarget, Raw.Proc.substituteCaptureAvoiding,
    Raw.Proc.captureRisk, Raw.Proc.substRaw] using step

/-- Tau propagates through canonical restriction as one native step. -/
theorem canonical_restriction_tau_native
    (world : World) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.restrict (.tau .zero) :
          SupportedProc world 0))
      .tau
      (SupportedProc.reifyAtWorld
        (.restrict .zero :
          SupportedProc world 0)) := by
  apply Late.NativeStep.restrict
  · simp [Raw.Action.names]
  · exact Late.NativeStep.prefixTau

/-- An old-name free output remains a native visible action under restriction. -/
theorem canonical_restriction_visible_output_native
    (world : World)
    (channel value : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.restrict
          (.output (.free channel) (.free value) .zero) :
            SupportedProc world 0))
      (.output channel.val value.val)
      (SupportedProc.reifyAtWorld
        (.restrict .zero :
          SupportedProc world 0)) := by
  apply Late.NativeStep.restrict
  · simp [Raw.Action.names]
    exact
      ⟨(ne_of_lt channel.isLt).symm,
        (ne_of_lt value.isLt).symm⟩
  · exact Late.NativeStep.prefixOutput

/-- Output of the restricted binder is one native bound-output extrusion. -/
theorem canonical_restriction_extrusion_native
    (world : World)
    (channel : Fin world) :
    Late.NativeStep
      (SupportedProc.reifyAtWorld
        (.restrict
          (.output (.free channel) (.bound (Fin.last 0)) .zero) :
            SupportedProc world 0))
      (.boundOutput channel.val world)
      .zero := by
  apply Late.NativeStep.open
  · exact (ne_of_lt channel.isLt).symm
  · exact Late.NativeStep.prefixOutput

end Cantilune.Pi.FMSCpoSupportedParallelRestriction
