import Cantilune.Pi.FMSCpoNondeterministicCardinalClosure

/-!
# The omega-closed subalgebra generated by a continuous map

For an arbitrary generator `X ⟶ U A`, this file constructs the intersection
of all carrier subsets of `A` that contain the generator image and are
closed under divergence, deadlock, choice, and omega-chain suprema.

The intersection is bundled as an actual `NDωCPO` object.  Its inclusion
into `A` is a strict continuous semilattice arrow, and the original
generator factors through it on the nose.

This closes the structural factorization half of the all-source
solution-set argument.  It deliberately does not claim the remaining
smallness theorem: one must still prove that this generated carrier has
cardinality at most `countableClosureBound X`, then choose a small family of
representatives and reindex every generated algebra into that family.
-/

noncomputable section

namespace Cantilune.Pi.FMSCpoNondeterministicGeneratedSubalgebra

open CategoryTheory
open OmegaCompletePartialOrder
open Cantilune.Pi.FMSExternalPackage
open Cantilune.Pi.FMSCpoNondeterministicCategory

namespace Generated

variable
    (source : ωCPO)
    (target : NDωCPO)
    (generator : source ⟶ NDωCPO.forget.obj target)

/--
A carrier subset closed under all structure required of an `NDωCPO`
subalgebra and containing the complete generator image.
-/
structure ClosedCarrier where
  carrier : Set target.carrier
  generator_mem : ∀ value, generator value ∈ carrier
  divergence_mem : target.computation.divergence ∈ carrier
  deadlock_mem : target.computation.deadlock ∈ carrier
  choice_mem :
    ∀ {left right},
      left ∈ carrier →
      right ∈ carrier →
      target.computation.choice (left, right) ∈ carrier
  omegaSup_mem :
    ∀ chain : Chain target.carrier,
      (∀ index, chain index ∈ carrier) →
      ωSup chain ∈ carrier

/--
The least closed carrier, defined as the intersection of every closed
carrier containing the generator image.
-/
def carrierSet : Set target.carrier :=
  { value |
    ∀ closed : ClosedCarrier source target generator,
      value ∈ closed.carrier }

theorem carrierSet_minimal
    (closed : ClosedCarrier source target generator) :
    carrierSet source target generator ⊆ closed.carrier :=
  fun _ member => member closed

theorem generator_mem (value : source) :
    generator value ∈ carrierSet source target generator :=
  fun closed => closed.generator_mem value

theorem divergence_mem :
    target.computation.divergence ∈
      carrierSet source target generator :=
  fun closed => closed.divergence_mem

theorem deadlock_mem :
    target.computation.deadlock ∈
      carrierSet source target generator :=
  fun closed => closed.deadlock_mem

theorem choice_mem
    {left right : target.carrier}
    (leftMember : left ∈ carrierSet source target generator)
    (rightMember : right ∈ carrierSet source target generator) :
    target.computation.choice (left, right) ∈
      carrierSet source target generator :=
  fun closed =>
    closed.choice_mem
      (leftMember closed)
      (rightMember closed)

theorem omegaSup_mem
    (chain : Chain target.carrier)
    (members :
      ∀ index,
        chain index ∈ carrierSet source target generator) :
    ωSup chain ∈ carrierSet source target generator :=
  fun closed =>
    closed.omegaSup_mem chain
      (fun index => members index closed)

/-- The actual generated carrier type. -/
abbrev Carrier :=
  { value : target.carrier //
    value ∈ carrierSet source target generator }

noncomputable instance carrierOmegaCompletePartialOrder :
    OmegaCompletePartialOrder
      (Carrier source target generator) :=
  OmegaCompletePartialOrder.subtype
    (carrierSet source target generator)
    (by
      intro chain members
      apply omegaSup_mem source target generator
      intro index
      exact
        members (chain index)
          ⟨index, rfl⟩)

/-- The generated subtype as an object of mathlib's `ωCPO`. -/
abbrev carrierCpo : ωCPO :=
  ωCPO.of (Carrier source target generator)

/-- Inclusion of the generated carrier into the ambient algebra carrier. -/
def inclusion :
    carrierCpo source target generator ⟶ target.carrier :=
  ContinuousHom.mk
    (OrderHom.Subtype.val
      (carrierSet source target generator))
    (fun _ => rfl)

@[simp]
theorem inclusion_apply
    (value : Carrier source target generator) :
    inclusion source target generator value =
      value.1 :=
  rfl

/-- Divergence restricted to the generated carrier. -/
def divergence :
    Carrier source target generator :=
  ⟨target.computation.divergence,
    divergence_mem source target generator⟩

/-- Deadlock restricted to the generated carrier. -/
def deadlock :
    Carrier source target generator :=
  ⟨target.computation.deadlock,
    deadlock_mem source target generator⟩

/-- Choice restricted to the generated carrier. -/
def choiceRaw
    (pair :
      Carrier source target generator ×
        Carrier source target generator) :
    Carrier source target generator :=
  ⟨target.computation.choice (pair.1.1, pair.2.1),
    choice_mem source target generator pair.1.2 pair.2.2⟩

theorem choiceRaw_monotone :
    Monotone (choiceRaw source target generator) := by
  intro left right ordered
  exact
    target.computation.choice.monotone
      ⟨ordered.1, ordered.2⟩

/-- Embed a pair of generated values into the ambient product carrier. -/
def pairInclusionOrderHom :
    (Carrier source target generator ×
      Carrier source target generator) →o
        (target.carrier × target.carrier) where
  toFun := fun pair => (pair.1.1, pair.2.1)
  monotone' := fun _ _ ordered => ordered

/-- The ambient pair chain underlying a generated pair chain. -/
def ambientPairChain
    (chain :
      Chain
        (Carrier source target generator ×
          Carrier source target generator)) :
    Chain (target.carrier × target.carrier) :=
  chain.map (pairInclusionOrderHom source target generator)

/-- Restricted choice is a genuine continuous operation. -/
def choice :
    ωCPO.of
        (Carrier source target generator ×
          Carrier source target generator) ⟶
      carrierCpo source target generator where
  toFun := choiceRaw source target generator
  monotone' := choiceRaw_monotone source target generator
  map_ωSup' := by
    intro chain
    apply Subtype.ext
    exact
      target.computation.choice.continuous
        (ambientPairChain source target generator chain)

@[simp]
theorem choice_apply
    (left right : Carrier source target generator) :
    choice source target generator (left, right) =
      choiceRaw source target generator (left, right) :=
  rfl

theorem choice_assoc
    (left middle right : Carrier source target generator) :
    choice source target generator
        (choice source target generator (left, middle), right) =
      choice source target generator
        (left, choice source target generator (middle, right)) := by
  apply Subtype.ext
  exact
    target.computation.choice_assoc
      left.1 middle.1 right.1

theorem choice_comm
    (left right : Carrier source target generator) :
    choice source target generator (left, right) =
      choice source target generator (right, left) := by
  apply Subtype.ext
  exact target.computation.choice_comm left.1 right.1

theorem choice_idem
    (value : Carrier source target generator) :
    choice source target generator (value, value) =
      value := by
  apply Subtype.ext
  exact target.computation.choice_idem value.1

theorem deadlock_choice
    (value : Carrier source target generator) :
    choice source target generator
        (deadlock source target generator, value) =
      value := by
  apply Subtype.ext
  exact target.computation.deadlock_choice value.1

theorem divergence_le
    (value : Carrier source target generator) :
    divergence source target generator ≤ value :=
  target.computation.divergence_le value.1

/-- The generated carrier bundled as an actual nondeterministic computation. -/
def computation : NondeterministicComputation where
  carrier := carrierCpo source target generator
  divergence := divergence source target generator
  divergence_le := divergence_le source target generator
  deadlock := deadlock source target generator
  choice := choice source target generator
  choice_assoc := choice_assoc source target generator
  choice_comm := choice_comm source target generator
  choice_idem := choice_idem source target generator
  deadlock_choice := deadlock_choice source target generator

/-- The generated subalgebra as an object of `NDωCPO`. -/
def object : NDωCPO where
  computation := computation source target generator

/--
The subtype inclusion is a strict continuous semilattice arrow into the
ambient target.
-/
def inclusionHom :
    object source target generator ⟶ target where
  hom := inclusion source target generator
  map_divergence := rfl
  map_deadlock := rfl
  map_choice := by
    intro _ _
    rfl

/-- The original generator with codomain restricted to the generated carrier. -/
def restrictedGenerator :
    source ⟶
      NDωCPO.forget.obj (object source target generator) where
  toFun := fun value =>
    ⟨generator value,
      generator_mem source target generator value⟩
  monotone' := fun _ _ ordered =>
    generator.monotone ordered
  map_ωSup' := by
    intro chain
    apply Subtype.ext
    exact generator.continuous chain

@[simp]
theorem restrictedGenerator_apply
    (value : source) :
    restrictedGenerator source target generator value =
      ⟨generator value,
        generator_mem source target generator value⟩ :=
  rfl

/--
Every generator factors through its generated `NDωCPO` subalgebra by a
strict continuous arrow, with literal one-step equality of carrier maps.
-/
theorem factorization :
    restrictedGenerator source target generator ≫
        NDωCPO.forget.map
          (inclusionHom source target generator) =
      generator := by
  apply ContinuousHom.ext
  intro value
  rfl

/-- The generated factorization represented in the comma category. -/
def structuredArrow :
    StructuredArrow source NDωCPO.forget :=
  StructuredArrow.mk
    (restrictedGenerator source target generator)

/-- The canonical comma-category arrow from the generated factorization. -/
def structuredFactor :
    structuredArrow source target generator ⟶
      StructuredArrow.mk generator :=
  StructuredArrow.homMk
    (inclusionHom source target generator)
    (factorization source target generator)

end Generated

end Cantilune.Pi.FMSCpoNondeterministicGeneratedSubalgebra
