import Cantilune.Pi.FMSExternalPackage

/-!
# Exact construction-level FMS acceptance boundary

`CompleteExternalFMSTheoremPackage` is intentionally provisional.  It fixes
the powerdomain, domain equation, action object, hiding, syntax denotation,
and full-abstraction statements, but it does not yet force restriction,
parallel, or the denotational transition relation to be *constructed* from
the domain equation.

This file states those remaining obligations as a stricter input package:

* restriction is a Kleisli fold over the four constructors of the exact FMS
  action shape;
* left merge is obtained by functorial action on the unrolled left process;
* synchronization is obtained from Fubini, an action-pair kernel, and monad
  multiplication;
* parallel is exactly the four-way nondeterministic choice of the two left
  merges and the two synchronization orientations; and
* stage-indexed transitions inspect `roll.inv`, with the closed operational
  transition relation identified with the world-zero instance.

No inhabitant of the strict package is defined here.  In particular, these
interfaces do not construct an Abramsky powerdomain or solve the CPO domain
equation.  The four `RestrictionActionFold` case operators are also supplied
construction data: a source-backed FMS instance must still identify them with
the recursive clauses of Table 2 (including last-name case analysis and
swap).

`PowerdomainObservation` is an additional Cantilune representation
hypothesis, not a theorem stated by FMS.  In particular, its exact
element-preimage laws for functorial action and multiplication must be
validated against the chosen free CPO algebra/powerdomain construction; they
must not be inferred from the abstract enriched adjunction alone.  The record
also leaves the observation of the distinguished divergence element
unconstrained.  Thus this module closes only a proposed *shape* of the
construction and the synchronization matrix.  It is not itself the missing
external theorem, and the observation interface remains subject to source
and model review before it can be an acceptance gate.
-/

noncomputable section

open CategoryTheory
open CategoryTheory.Limits

namespace Cantilune.Pi.FMSExactAcceptance

open Cantilune.Pi.FMSModel
open Cantilune.Pi.FMSExternalPackage

/-- The exact action-layer CPO occurring under the powerdomain. -/
abbrev ActionLayer
    (package : CompleteExternalFMSTheoremPackage)
    (world : World) : ωCPO :=
  (package.domain.actionFunctor.obj package.domain.agent).obj world

/-- Re-encode the concrete four-branch action carrier in the domain layer. -/
def encodeAction
    (package : CompleteExternalFMSTheoremPackage)
    (world : World)
    (action : ActionCarrier package.domain.agent world) :
    ActionLayer package world :=
  (package.domain.actionShape package.domain.agent world).symm action

/-- Unroll one agent into the powerdomain of exact FMS actions. -/
def unroll
    (package : CompleteExternalFMSTheoremPackage)
    (world : World)
    (process : package.domain.agent.obj world) :
    package.powerdomain.monad.obj (ActionLayer package world) :=
  package.domain.roll.inv.app world process

/--
The concrete product carrier mapped into mathlib's chosen categorical binary
product.  The latter is implemented as a finite pi-type and is therefore not
definitionally the ordinary Lean pair type.
-/
def toCategoricalProduct (left right : ωCPO) :
    ωCPO.of (left × right) ⟶ (left ⨯ right) :=
  Limits.prod.lift
    (OmegaCompletePartialOrder.ContinuousHom.ofFun
      (fun pair : left × right => pair.1))
    (OmegaCompletePartialOrder.ContinuousHom.ofFun
      (fun pair : left × right => pair.2))

/--
An extensional observation interface proposed for the supplied powerdomain.

This is a local strengthening, not an unpacking of the FMS full-abstraction
theorem.  The equations prevent a provider from choosing an unrelated
relation after seeing the desired operational theorem: observation is
generated by unit, empty, choice, functorial action, and multiplication.
However, an abstract free CPO-algebra adjunction does not by itself provide
this element relation or the exact preimage equations below.  A concrete
Abramsky-powerdomain construction must prove them (or this interface must be
revised to its closure/approximation semantics).  No equation below currently
specifies observations of `powerdomain.divergence`.
-/
structure PowerdomainObservation
    (package : CompleteExternalFMSTheoremPackage) where
  observes :
    ∀ {object : ωCPO},
      package.powerdomain.monad.obj object → object → Prop
  unit_iff :
    ∀ {object : ωCPO} (value candidate : object),
      observes (package.powerdomain.monad.η.app object value) candidate ↔
        candidate = value
  empty_iff :
    ∀ {object : ωCPO} (candidate : object),
      ¬ observes (package.powerdomain.empty object) candidate
  choice_iff :
    ∀ {object : ωCPO}
      (left right : package.powerdomain.monad.obj object)
      (candidate : object),
      observes (package.powerdomain.choice object (left, right)) candidate ↔
        observes left candidate ∨ observes right candidate
  map_iff :
    ∀ {source target : ωCPO} (morphism : source ⟶ target)
      (computation : package.powerdomain.monad.obj source)
      (candidate : target),
      observes (package.powerdomain.monad.map morphism computation) candidate ↔
        ∃ original,
          observes computation original ∧ morphism original = candidate
  multiplication_iff :
    ∀ {object : ωCPO}
      (computation :
        package.powerdomain.monad.obj
          (package.powerdomain.monad.obj object))
      (candidate : object),
      observes
          (package.powerdomain.monad.μ.app object computation) candidate ↔
        ∃ inner,
          observes computation inner ∧ observes inner candidate

/--
The stage-indexed denotational transition relation is a definition: unroll
the domain equation and observe the encoded action.  It is not a freely
supplied ternary relation.
-/
def StageTransition
    (package : CompleteExternalFMSTheoremPackage)
    (observation : PowerdomainObservation package)
    (world : World)
    (source : package.domain.agent.obj world)
    (action : ActionCarrier package.domain.agent world) : Prop :=
  observation.observes
    (unroll package world source)
    (encodeAction package world action)

/--
At closed world zero the only possible exact action constructor is `tau`;
all channel-bearing constructors contain an impossible `Fin 0`.
-/
def RealizesClosedAction
    {package : CompleteExternalFMSTheoremPackage} :
    ActionCarrier package.domain.agent 0 →
      Raw.Action → package.domain.agent.obj 0 → Prop
  | .input channel _known _fresh, _, _ => Fin.elim0 channel
  | .freeOutput channel _value _continuation, _, _ => Fin.elim0 channel
  | .boundOutput channel _continuation, _, _ => Fin.elim0 channel
  | .tau continuation, label, target =>
      label = .tau ∧ continuation = target

/-! ## Restriction as an action-algebra fold -/

/--
Construction-level restriction.

`fold world known` maps each action at the extended world to a
nondeterministic action at the old world.  The four branch equations expose
the complete action algebra.  `restriction_unroll` then requires `res` to be
the corresponding Kleisli fold, not an unrelated continuous map.
-/
structure RestrictionActionFold
    (package : CompleteExternalFMSTheoremPackage) where
  fold :
    ∀ (world : World)
      (_known : Fin world → package.domain.agent.obj world),
      ActionLayer package (world + 1) ⟶
        package.powerdomain.monad.obj (ActionLayer package world)
  inputCase :
    ∀ (world : World)
      (_known : Fin world → package.domain.agent.obj world)
      (_channel : Fin (world + 1))
      (_continuations :
        Fin (world + 1) → package.domain.agent.obj (world + 1))
      (_fresh : package.domain.agent.obj (world + 2)),
      package.powerdomain.monad.obj (ActionLayer package world)
  freeOutputCase :
    ∀ (world : World)
      (_known : Fin world → package.domain.agent.obj world)
      (_channel _value : Fin (world + 1))
      (_continuation : package.domain.agent.obj (world + 1)),
      package.powerdomain.monad.obj (ActionLayer package world)
  boundOutputCase :
    ∀ (world : World)
      (_known : Fin world → package.domain.agent.obj world)
      (_channel : Fin (world + 1))
      (_continuation : package.domain.agent.obj (world + 2)),
      package.powerdomain.monad.obj (ActionLayer package world)
  tauCase :
    ∀ (world : World)
      (_known : Fin world → package.domain.agent.obj world)
      (_continuation : package.domain.agent.obj (world + 1)),
      package.powerdomain.monad.obj (ActionLayer package world)
  fold_input :
    ∀ world known channel continuations fresh,
      fold world known
          (encodeAction package (world + 1)
            (.input channel continuations fresh)) =
        inputCase world known channel continuations fresh
  fold_freeOutput :
    ∀ world known channel value continuation,
      fold world known
          (encodeAction package (world + 1)
            (.freeOutput channel value continuation)) =
        freeOutputCase world known channel value continuation
  fold_boundOutput :
    ∀ world known channel continuation,
      fold world known
          (encodeAction package (world + 1)
            (.boundOutput channel continuation)) =
        boundOutputCase world known channel continuation
  fold_tau :
    ∀ world known continuation,
      fold world known
          (encodeAction package (world + 1) (.tau continuation)) =
        tauCase world known continuation
  restriction_unroll :
    ∀ world known fresh,
      unroll package world
          (package.domain.res world (known, fresh)) =
        package.powerdomain.monad.μ.app (ActionLayer package world)
          (package.powerdomain.monad.map (fold world known)
            (unroll package (world + 1) fresh))

/-! ## Left merge, synchronization, and four-way parallel -/

/-- A continuous binary agent operation natural in finite-world injections. -/
structure NaturalBinaryOperation
    (package : CompleteExternalFMSTheoremPackage) where
  app :
    ∀ world,
      ωCPO.of
          (package.domain.agent.obj world ×
            package.domain.agent.obj world) ⟶
        package.domain.agent.obj world
  natural :
    ∀ {source target : World} (injection : source ⟶ target)
      (left right : package.domain.agent.obj source),
      package.domain.agent.map injection (app source (left, right)) =
        app target
          (package.domain.agent.map injection left,
            package.domain.agent.map injection right)

/--
Exactly the four ordered action pairs which may synchronize in late pi.
Channel equality is part of the predicate; all remaining cells of the
four-by-four action matrix must denote deadlock.
-/
def CanSynchronize
    {model : World ⥤ ωCPO} {world : World} :
    ActionCarrier model world → ActionCarrier model world → Prop
  | .input inputChannel _ _, .freeOutput outputChannel _ _ =>
      inputChannel = outputChannel
  | .freeOutput outputChannel _ _, .input inputChannel _ _ =>
      inputChannel = outputChannel
  | .input inputChannel _ _, .boundOutput outputChannel _ =>
      inputChannel = outputChannel
  | .boundOutput outputChannel _, .input inputChannel _ _ =>
      inputChannel = outputChannel
  | _, _ => False

/--
The action-level construction of left merge and synchronization.

The free/bound synchronization equations use actual FMS action constructors.
Bound communication additionally exposes the non-injective specialization of
the fresh output continuation; this operation cannot be fabricated from the
finite-injection world functor.
-/
structure ParallelConstruction
    (package : CompleteExternalFMSTheoremPackage) where
  parallel : NaturalBinaryOperation package
  leftMerge : NaturalBinaryOperation package
  synchronize : NaturalBinaryOperation package

  specialize :
    ∀ (world : World) (_name : Fin world),
      package.domain.agent.obj (world + 1) ⟶
        package.domain.agent.obj world
  specialize_weakened :
    ∀ world name (process : package.domain.agent.obj world),
      specialize world name
          (package.domain.agent.map (FMSModel.up world) process) =
        process

  leftAction :
    ∀ (world : World) (_right : package.domain.agent.obj world),
      ActionLayer package world ⟶ ActionLayer package world
  leftAction_input :
    ∀ world right channel known fresh,
      package.domain.actionShape package.domain.agent world
          (leftAction world right
            (encodeAction package world (.input channel known fresh))) =
        .input channel
          (fun name => parallel.app world (known name, right))
          (parallel.app (world + 1)
            (fresh,
              package.domain.agent.map (FMSModel.up world) right))
  leftAction_freeOutput :
    ∀ world right channel value continuation,
      package.domain.actionShape package.domain.agent world
          (leftAction world right
            (encodeAction package world
              (.freeOutput channel value continuation))) =
        .freeOutput channel value
          (parallel.app world (continuation, right))
  leftAction_boundOutput :
    ∀ world right channel continuation,
      package.domain.actionShape package.domain.agent world
          (leftAction world right
            (encodeAction package world
              (.boundOutput channel continuation))) =
        .boundOutput channel
          (parallel.app (world + 1)
            (continuation,
              package.domain.agent.map (FMSModel.up world) right))
  leftAction_tau :
    ∀ world right continuation,
      package.domain.actionShape package.domain.agent world
          (leftAction world right
            (encodeAction package world (.tau continuation))) =
        .tau (parallel.app world (continuation, right))
  leftMerge_unroll :
    ∀ world left right,
      unroll package world (leftMerge.app world (left, right)) =
        package.powerdomain.monad.map (leftAction world right)
          (unroll package world left)

  syncAction :
    ∀ world,
      (ActionLayer package world ⨯ ActionLayer package world) ⟶
        package.powerdomain.monad.obj (ActionLayer package world)
  syncAction_natural :
    ∀ {source target : World} (injection : source ⟶ target),
      Limits.prod.map
          ((package.domain.actionFunctor.obj package.domain.agent).map
            injection)
          ((package.domain.actionFunctor.obj package.domain.agent).map
            injection) ≫
          syncAction target =
        syncAction source ≫
          package.powerdomain.monad.map
            ((package.domain.actionFunctor.obj package.domain.agent).map
              injection)
  sync_input_freeOutput :
    ∀ world channel known fresh value continuation,
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world (.input channel known fresh),
              encodeAction package world
                (.freeOutput channel value continuation))) =
        package.powerdomain.monad.η.app (ActionLayer package world)
          (encodeAction package world
            (.tau (parallel.app world (known value, continuation))))
  sync_freeOutput_input :
    ∀ world channel value continuation known fresh,
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world
                (.freeOutput channel value continuation),
              encodeAction package world (.input channel known fresh))) =
        package.powerdomain.monad.η.app (ActionLayer package world)
          (encodeAction package world
            (.tau (parallel.app world (continuation, known value))))
  sync_input_boundOutput :
    ∀ world channel known fresh continuation,
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world (.input channel known fresh),
              encodeAction package world
                (.boundOutput channel continuation))) =
        package.powerdomain.monad.η.app (ActionLayer package world)
          (encodeAction package world
            (.tau
              (package.domain.res world
                ((fun name =>
                    parallel.app world
                      (known name, specialize world name continuation)),
                  parallel.app (world + 1) (fresh, continuation)))))
  sync_boundOutput_input :
    ∀ world channel continuation known fresh,
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world
                (.boundOutput channel continuation),
              encodeAction package world (.input channel known fresh))) =
        package.powerdomain.monad.η.app (ActionLayer package world)
          (encodeAction package world
            (.tau
              (package.domain.res world
                ((fun name =>
                    parallel.app world
                      (specialize world name continuation, known name)),
                  parallel.app (world + 1) (continuation, fresh)))))
  sync_input_freeOutput_mismatch :
    ∀ world channel inputChannel known fresh value continuation,
      channel ≠ inputChannel →
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world
                (.input inputChannel known fresh),
              encodeAction package world
                (.freeOutput channel value continuation))) =
        package.powerdomain.empty (ActionLayer package world)
  sync_freeOutput_input_mismatch :
    ∀ world channel inputChannel value continuation known fresh,
      channel ≠ inputChannel →
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world
                (.freeOutput channel value continuation),
              encodeAction package world
                (.input inputChannel known fresh))) =
        package.powerdomain.empty (ActionLayer package world)
  syncAction_no_handshake :
    ∀ world
      (left right : ActionCarrier package.domain.agent world),
      ¬ CanSynchronize left right →
      syncAction world
          (toCategoricalProduct
            (ActionLayer package world) (ActionLayer package world)
            (encodeAction package world left,
              encodeAction package world right)) =
        package.powerdomain.empty (ActionLayer package world)
  synchronize_unroll :
    ∀ world left right,
      unroll package world (synchronize.app world (left, right)) =
        package.powerdomain.monad.μ.app (ActionLayer package world)
          (package.powerdomain.monad.map (syncAction world)
            (package.powerdomain.fubini
              (ActionLayer package world) (ActionLayer package world)
              (toCategoricalProduct
                (package.powerdomain.monad.obj (ActionLayer package world))
                (package.powerdomain.monad.obj (ActionLayer package world))
                (unroll package world left, unroll package world right))))

  parallel_four_way :
    ∀ world left right,
      parallel.app world (left, right) =
        package.domain.choice world
          (leftMerge.app world (left, right))
          (package.domain.choice world
            (leftMerge.app world (right, left))
            (package.domain.choice world
              (synchronize.app world (left, right))
              (synchronize.app world (right, left))))

/--
The strict construction-level package.

No value is supplied by Cantilune.  A provider must first construct the
already-provisional complete FMS package and then discharge the additional
fold, left-merge, synchronization, and stage-transition equations.  Acceptance
of a genuine FMS instance additionally requires the supplied restriction case
operators to be audited against the source Table-2 formulas, validation (or
revision) of the extra `PowerdomainObservation` laws, and coverage of the
guarded-replication syntax used by the source's full theorem.
-/
structure ExactFMSAcceptancePackage where
  base : CompleteExternalFMSTheoremPackage
  observation : PowerdomainObservation base
  restrictionAction : RestrictionActionFold base
  parallelConstruction : ParallelConstruction base
  compositional_parallel_agrees :
    ∀ world left right,
      base.compositionalInterpretation.parallel world (left, right) =
        parallelConstruction.parallel.app world (left, right)
  late_transition_derived :
    ∀ source label target,
      base.lateFullAbstraction.transition
          (base.lateFullAbstraction.denote source) label target ↔
        ∃ action : ActionCarrier base.domain.agent 0,
          StageTransition base observation 0
              (base.lateFullAbstraction.denote source) action ∧
            RealizesClosedAction action label target

/-- Availability of the exact construction remains an explicit proposition. -/
def ExactFMSAvailable : Prop :=
  Nonempty ExactFMSAcceptancePackage

namespace ExactFMSAcceptancePackage

/-- Consumer theorem exposing the constructed stage-zero transition. -/
theorem transition_iff_unrolled_stage
    (package : ExactFMSAcceptancePackage)
    (source : ClosedRaw) (label : Raw.Action)
    (target : package.base.domain.agent.obj 0) :
    package.base.lateFullAbstraction.transition
          (package.base.lateFullAbstraction.denote source) label target ↔
      ∃ action : ActionCarrier package.base.domain.agent 0,
        StageTransition package.base package.observation 0
            (package.base.lateFullAbstraction.denote source) action ∧
          RealizesClosedAction action label target :=
  package.late_transition_derived source label target

/-- Consumer theorem exposing the exact four-way parallel equation. -/
theorem parallel_is_four_way_choice
    (package : ExactFMSAcceptancePackage)
    (world : World)
    (left right : package.base.domain.agent.obj world) :
    package.parallelConstruction.parallel.app world (left, right) =
      package.base.domain.choice world
        (package.parallelConstruction.leftMerge.app world (left, right))
        (package.base.domain.choice world
          (package.parallelConstruction.leftMerge.app world (right, left))
          (package.base.domain.choice world
            (package.parallelConstruction.synchronize.app world (left, right))
            (package.parallelConstruction.synchronize.app world
              (right, left)))) :=
  package.parallelConstruction.parallel_four_way world left right

end ExactFMSAcceptancePackage

end Cantilune.Pi.FMSExactAcceptance
