import Cantilune.Pi.FMSCpoUnseparatedSourceCore

/-!
# Finite strong-observation obstruction for an unseparated effect

This file isolates a consequence of the ratified D1-A equations which is
independent of any particular carrier presentation.

If inactive process denotes the least computation, nondeterministic choice is
semilattice supremum, and tau prefix is monotone, then

`tau.0 + tau.tau.0`

has the same denotation as `tau.tau.0`.  The two finite syntax trees are
nevertheless distinct under constructor-sensitive strong observation.
Consequently D1-A cannot support a full-abstraction statement whose
operational equivalence distinguishes those trees.  A positive theorem must
instead use the bottom/Hoare observation induced by the unseparated effect, or
move the deadlock distinction to the already separate native and terminal
layers.
-/

namespace Cantilune.Pi.FMSUnseparatedFiniteStrongNoGo

/-- The smallest finite fragment needed by the obstruction. -/
inductive FiniteTauChoice where
  | inactive
  | tauInactive
  | tauTauInactive
  | absorbedChoice
  deriving DecidableEq

/-- The strong one-step semantics of the finite fragment. -/
inductive Step : FiniteTauChoice → FiniteTauChoice → Prop
  | tauInactive : Step .tauInactive .inactive
  | tauTauInactive : Step .tauTauInactive .tauInactive
  | absorbedLeft : Step .absorbedChoice .inactive
  | absorbedRight : Step .absorbedChoice .tauInactive

/-- A symmetric strong bisimulation for the finite fragment. -/
def IsStrongBisimulation
    (relation : FiniteTauChoice → FiniteTauChoice → Prop) : Prop :=
  (∀ {left right}, relation left right → relation right left) ∧
  ∀ {left right},
    relation left right →
    ∀ {leftTarget},
      Step left leftTarget →
      ∃ rightTarget,
        Step right rightTarget ∧
        relation leftTarget rightTarget

/-- Strong bisimilarity generated by the native finite transition system. -/
def StronglyEquivalent
    (left right : FiniteTauChoice) : Prop :=
  ∃ relation,
    IsStrongBisimulation relation ∧
    relation left right

/-- Interpretation of the fragment in any D1-A ordered semilattice carrier. -/
def denote
    {Carrier : Type*}
    [SemilatticeSup Carrier] [OrderBot Carrier]
    (tau : Carrier → Carrier)
    (program : FiniteTauChoice) : Carrier :=
  match program with
  | .inactive => ⊥
  | .tauInactive => tau ⊥
  | .tauTauInactive => tau (tau ⊥)
  | .absorbedChoice => tau ⊥ ⊔ tau (tau ⊥)

/--
The finite choice is absorbed in every D1-A carrier with monotone tau prefix.
-/
theorem absorbedChoice_denotation_eq
    {Carrier : Type*}
    [SemilatticeSup Carrier] [OrderBot Carrier]
    (tau : Carrier → Carrier)
    (tauMonotone : Monotone tau) :
    denote tau .absorbedChoice =
      denote tau .tauTauInactive := by
  apply sup_eq_right.mpr
  exact tauMonotone bot_le

/-- The two finite programs remain distinct under strong observation. -/
theorem absorbedChoice_not_stronglyEquivalent :
    ¬ StronglyEquivalent
      .absorbedChoice .tauTauInactive := by
  rintro ⟨relation, bisimulation, related⟩
  obtain ⟨rightTarget, rightStep, targetsRelated⟩ :=
    bisimulation.2 related Step.absorbedLeft
  cases rightStep
  have reversed :
      relation .tauInactive .inactive :=
    bisimulation.1 targetsRelated
  obtain ⟨inactiveTarget, impossible, _⟩ :=
    bisimulation.2 reversed Step.tauInactive
  cases impossible

/--
A strong full-abstraction claim for this finite fragment is contradictory.
-/
def StrongFullAbstract
    {Carrier : Type*}
    [SemilatticeSup Carrier] [OrderBot Carrier]
    (tau : Carrier → Carrier) : Prop :=
  ∀ left right,
    denote tau left = denote tau right ↔
      StronglyEquivalent left right

/--
Kernel no-go for constructor-sensitive strong full abstraction under the
three D1-A equations used above.
-/
theorem not_strongFullAbstract
    {Carrier : Type*}
    [SemilatticeSup Carrier] [OrderBot Carrier]
    (tau : Carrier → Carrier)
    (tauMonotone : Monotone tau) :
    ¬ StrongFullAbstract tau := by
  intro full
  have equivalent :
      StronglyEquivalent
        .absorbedChoice .tauTauInactive :=
    (full .absorbedChoice .tauTauInactive).mp
      (absorbedChoice_denotation_eq tau tauMonotone)
  exact absorbedChoice_not_stronglyEquivalent equivalent

end Cantilune.Pi.FMSUnseparatedFiniteStrongNoGo
