import Cantilune.Pi.P1cCriticalMultistageCertificate

/-!
# Full-native refinement of all fifteen P1c reference families

`P1cProjectionCertificates.PiTarget` records one designated derivation per
event.  Its target relation is intentionally event-indexed and therefore
does not classify every transition of the underlying standard late-pi
process.

This module gives the stronger operational construction.  A target state
retains a family tag only to distinguish independently audited protocols and
their signature versions; its transition relation contains **every**
`Late.NativeStep` of the carried `Raw.Proc`.  It is not generated by the
source relation and it has no weak or transitive closure.

The two protocols whose first step establishes a live session (`openClose`
and `restriction`) receive an explicit intermediate state and payload event.
Dynamic partner admission also has an explicit admitted/reconnect phase: its
visible input derivative is the canonical reconnect-ready process and a
subsequent genuine tau step completes that phase.  All other designated
endpoints are proved native-terminal.  The resulting
certificate therefore proves soundness, reflection/exhaustiveness, success,
waiting, and signature-version preservation for all fifteen initial event
families.
-/

namespace Cantilune.Pi.P1cFullNativeRefinement

open Cantilune.Core
open Cantilune.Pi
open Cantilune.Pi.Protocols
open Cantilune.Pi.P1cMatrix
open Cantilune.Pi.P1cClosedNativeCertificate
open Cantilune.Pi.P1cCriticalMultistageCertificate
open Cantilune.Pi.P1cLateExhaustiveness

/-! ## Refined source protocol -/

/--
Every original P1c event still starts at `ready event`.  The two session
establishment families have one additional state before their common payload
completion.
-/
inductive State where
  | ready (event : SourceEvent)
  | openCloseEstablished
  | restrictionEstablished
  | admissionEstablished
  | completed (event : SourceEvent)
  deriving DecidableEq, Repr, Fintype

/--
`execute event` is the original event identity.  The three phase labels
expose native follow-ups which a two-state source cannot reflect.
-/
inductive Event where
  | execute (event : SourceEvent)
  | openClosePayload
  | restrictionPayload
  | admissionReconnect
  deriving DecidableEq, Repr, Fintype

def afterFirst : SourceEvent → State
  | .openClose => .openCloseEstablished
  | .restriction => .restrictionEstablished
  | .dynamicPartnerAdmission => .admissionEstablished
  | event => .completed event

inductive Step : State → Event → State → Prop where
  | execute (event : SourceEvent) :
      Step (.ready event) (.execute event) (afterFirst event)
  | openClosePayload :
      Step .openCloseEstablished .openClosePayload (.completed .openClose)
  | restrictionPayload :
      Step .restrictionEstablished .restrictionPayload
        (.completed .restriction)
  | admissionReconnect :
      Step .admissionEstablished .admissionReconnect
        (.completed .dynamicPartnerAdmission)

def sourceSuccess : State → Prop
  | .completed _ => True
  | .ready _
  | .openCloseEstablished
  | .restrictionEstablished
  | .admissionEstablished => False

def sourceVersion : State → Nat
  | .admissionEstablished
  | .completed .dynamicPartnerAdmission => 1
  | _ => 0

def sourceLTS : ObservableLTS where
  State := State
  Event := Event
  stateSetoid := ObservableLTS.equalitySetoid State
  step := Step
  observable := fun _ => True
  success := sourceSuccess
  waiting := fun _ => False
  signatureVersion := sourceVersion
  step_congr := by
    intro source source' event target target' sourceEq targetEq
    subst source'
    subst target'
    rfl
  success_congr := by
    intro source target equality
    subst target
    rfl
  waiting_congr := by
    intro source target equality
    subst target
    rfl
  signatureVersion_congr := by
    intro source target equality
    subst target
    rfl

/-! ## Actual raw processes and the complete native target -/

/--
Closed encodings are used exactly where an open parallel offer would expose
an additional environmental branch.  Prefix events remain genuinely open
and keep their visible native labels.
-/
def readyProcess : SourceEvent → Raw.Proc
  | .freeOutput => messageSender.erase
  | .boundOutput =>
      (.new delegated (.send delegationChannel delegated .zero) : Proc).erase
  | .lateInput => messageReceiver.erase
  | .communication => closedCommunicationSource.erase
  | .openClose => closedOpenCloseSource.erase
  | .restriction => closedRestrictedHandshake.erase
  | .scopeExtrusion =>
      (.new session (.send publicChannel session .zero) : Proc).erase
  | .delegation => closedReconnectSource.erase
  | .choiceLeft => (.choice (.tau .zero) .zero : Proc).erase
  | .choiceRight => (.choice .zero (.tau .zero) : Proc).erase
  | .matchSuccess => (.matchEq payload payload (.tau .zero) : Proc).erase
  | .mismatchGuard => mismatchDecision.erase
  | .dynamicPartnerAdmission =>
      .recv delegationBus delegatedBinder closedReconnectSource.erase
  | .instanceReconnect => closedReconnectSource.erase
  | .instanceDeleteQuiescent => closedQuiescentDeleteSource.erase

def firstAction : SourceEvent → Raw.Action
  | .freeOutput => .output session payload
  | .boundOutput => .boundOutput delegationBus delegated
  | .lateInput => .input session payloadBinder
  | .communication
  | .openClose
  | .restriction => .tau
  | .scopeExtrusion => .boundOutput publicName session
  | .delegation
  | .choiceLeft
  | .choiceRight
  | .matchSuccess
  | .mismatchGuard => .tau
  | .dynamicPartnerAdmission => .input delegationBus delegatedBinder
  | .instanceReconnect
  | .instanceDeleteQuiescent => .tau

/-- Endpoint of the first native step, before any required payload follow-up. -/
def firstTarget : SourceEvent → Raw.Proc
  | .freeOutput
  | .boundOutput
  | .lateInput => .zero
  | .communication => closedCommunicationTarget.erase
  | .openClose => closedOpenCloseTarget.erase
  | .restriction => closedHandshakeResult.erase
  | .scopeExtrusion => .zero
  | .delegation => closedReconnectTarget.erase
  | .choiceLeft
  | .choiceRight
  | .matchSuccess
  | .mismatchGuard => .zero
  | .dynamicPartnerAdmission => closedReconnectSource.erase
  | .instanceReconnect => closedReconnectTarget.erase
  | .instanceDeleteQuiescent => closedQuiescentDeleteTarget.erase

/-- Family-specific terminal raw process. -/
def terminalProcess : SourceEvent → Raw.Proc
  | .freeOutput
  | .boundOutput
  | .lateInput => .zero
  | .communication => closedCommunicationTarget.erase
  | .openClose => closedCompletedProcess.erase
  | .restriction => closedCompletedProcess.erase
  | .scopeExtrusion => .zero
  | .delegation => closedReconnectTarget.erase
  | .choiceLeft
  | .choiceRight
  | .matchSuccess
  | .mismatchGuard => .zero
  | .dynamicPartnerAdmission => closedReconnectTarget.erase
  | .instanceReconnect => closedReconnectTarget.erase
  | .instanceDeleteQuiescent => closedQuiescentDeleteTarget.erase

def stateFamily : State → SourceEvent
  | .ready event => event
  | .openCloseEstablished => .openClose
  | .restrictionEstablished => .restriction
  | .admissionEstablished => .dynamicPartnerAdmission
  | .completed event => event

def stateProcess : State → Raw.Proc
  | .ready event => readyProcess event
  | .openCloseEstablished => closedOpenCloseTarget.erase
  | .restrictionEstablished => closedHandshakeResult.erase
  | .admissionEstablished => closedReconnectSource.erase
  | .completed event => terminalProcess event

/--
A family tag plus an actual raw process.  The tag is observational metadata;
`TargetStep` below admits every native derivative of `process`.
-/
structure TargetState where
  family : SourceEvent
  process : Raw.Proc
  deriving DecidableEq, Repr

inductive TargetStep : TargetState → Raw.Action → TargetState → Prop where
  | native (family : SourceEvent)
      {process : Raw.Proc} {action : Raw.Action} {next : Raw.Proc}
      (step : Late.NativeStep process action next) :
      TargetStep ⟨family, process⟩ action ⟨family, next⟩

def mapState (state : State) : TargetState :=
  ⟨stateFamily state, stateProcess state⟩

def mapEvent : Event → Raw.Action
  | .execute event => firstAction event
  | .openClosePayload
  | .restrictionPayload
  | .admissionReconnect => .tau

def targetSuccess (state : TargetState) : Prop :=
  state.process = terminalProcess state.family

def targetVersion (state : TargetState) : Nat :=
  if state.family = .dynamicPartnerAdmission ∧
      (state.process = firstTarget .dynamicPartnerAdmission ∨
        state.process = terminalProcess .dynamicPartnerAdmission) then
    1
  else
    0

/--
The independently declared complete target LTS.  No observation filter
removes environmental transitions.
-/
def targetLTS : ObservableLTS where
  State := TargetState
  Event := Raw.Action
  stateSetoid := ObservableLTS.equalitySetoid TargetState
  step := TargetStep
  observable := fun _ => True
  success := targetSuccess
  waiting := fun _ => False
  signatureVersion := targetVersion
  step_congr := by
    intro source source' event target target' sourceEq targetEq
    subst source'
    subst target'
    rfl
  success_congr := by
    intro source target equality
    subst target
    rfl
  waiting_congr := by
    intro source target equality
    subst target
    rfl
  signatureVersion_congr := by
    intro source target equality
    subst target
    rfl

/-! ## Exact native classifications for the remaining elementary families -/

private theorem zero_no_native
    {action : Raw.Action} {target : Raw.Proc} :
    ¬ Late.NativeStep .zero action target := by
  intro step
  cases step

private theorem send_native_exact
    {channel value : Name} {continuation : Raw.Proc}
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep (.send channel value continuation) action target) :
    action = .output channel value ∧ target = continuation := by
  cases step
  exact ⟨rfl, rfl⟩

private theorem receive_native_exact
    {channel binder : Name} {continuation : Raw.Proc}
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep (.recv channel binder continuation) action target) :
    action = .input channel binder ∧ target = continuation := by
  cases step
  exact ⟨rfl, rfl⟩

private theorem restricted_self_send_native_exact
    {fresh channel : Name} (_distinct : fresh ≠ channel)
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep
        (.new fresh (.send channel fresh .zero)) action target) :
    action = .boundOutput channel fresh ∧ target = .zero := by
  cases step with
  | restrict freshness bodyStep =>
      cases bodyStep
      exact False.elim (freshness (by simp [Raw.Action.names]))
  | «open» channelDistinct bodyStep =>
      cases bodyStep
      exact ⟨rfl, rfl⟩

private theorem choice_left_native_exact
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep
        (.choice (.tau .zero) .zero) action target) :
    action = .tau ∧ target = .zero := by
  cases step with
  | choiceLeft inner =>
      cases inner
      exact ⟨rfl, rfl⟩
  | choiceRight inner =>
      exact False.elim (zero_no_native inner)

private theorem choice_right_native_exact
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep
        (.choice .zero (.tau .zero)) action target) :
    action = .tau ∧ target = .zero := by
  cases step with
  | choiceLeft inner =>
      exact False.elim (zero_no_native inner)
  | choiceRight inner =>
      cases inner
      exact ⟨rfl, rfl⟩

private theorem match_native_exact
    {name : Name} {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep
        (.matchEq name name (.tau .zero)) action target) :
    action = .tau ∧ target = .zero := by
  cases step with
  | matchGuard inner =>
      cases inner
      exact ⟨rfl, rfl⟩

private theorem mismatch_native_exact'
    {left right : Name} (_distinct : left ≠ right)
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep
        (.matchNe left right (.tau .zero)) action target) :
    action = .tau ∧ target = .zero := by
  cases step with
  | mismatchGuard _ inner =>
      cases inner
      exact ⟨rfl, rfl⟩

private theorem raw_restriction_substitution :
    (Raw.Proc.recv sessionBinder payloadBinder .zero).substituteCaptureAvoiding
        sessionBinder session =
      .recv session payloadBinder .zero := by
  decide

/--
The closed `res(com)` requesting process has exactly its handshake tau step.
This is the raw standard-late analogue of the typed request/accept uniqueness
lemma.
-/
private theorem closed_restriction_native_exact
    {action : Raw.Action} {target : Raw.Proc}
    (step :
      Late.NativeStep closedRestrictedHandshake.erase action target) :
    action = .tau ∧ target = closedHandshakeResult.erase := by
  change
    Late.NativeStep
      (.new publicName
        (.new session
          (.par
            (.send publicName session
              (.send session payload .zero))
            (.recv publicName sessionBinder
              (.recv sessionBinder payloadBinder .zero)))))
      action target at step
  cases step with
  | restrict publicFresh sessionStep =>
      cases sessionStep with
      | restrict sessionFresh bodyStep =>
          cases bodyStep with
          | parLeft _ senderStep =>
              cases senderStep
              exact False.elim
                (sessionFresh (by simp [Raw.Action.names, session]))
          | parRight _ receiverStep =>
              cases receiverStep
              exact False.elim
                (publicFresh (by simp [Raw.Action.names, publicName]))
          | syncLeft outputStep inputStep binderFresh =>
              cases outputStep
              cases inputStep
              rw [raw_restriction_substitution]
              exact ⟨rfl, rfl⟩
          | syncRight inputStep outputStep binderFresh =>
              cases inputStep
          | closeLeft outputStep inputStep freshForReceiver binderFresh =>
              cases outputStep
          | closeRight inputStep outputStep freshForReceiver binderFresh =>
              cases inputStep
      | «open» _ bodyStep =>
          cases bodyStep with
          | parLeft _ senderStep =>
              cases senderStep
              exact False.elim
                (publicFresh (by simp [Raw.Action.names, publicName]))
          | parRight _ receiverStep =>
              cases receiverStep
  | «open» _ sessionStep =>
      cases sessionStep with
      | restrict sessionFresh bodyStep =>
          cases bodyStep with
          | parLeft _ senderStep =>
              cases senderStep
          | parRight _ receiverStep =>
              cases receiverStep

/-! ## Soundness and exhaustive reflection -/

/-- Every one of the fifteen original events has its genuine first step. -/
theorem first_native (event : SourceEvent) :
    Late.NativeStep
      (readyProcess event) (firstAction event) (firstTarget event) := by
  cases event with
  | freeOutput =>
      exact Late.NativeStep.prefixOutput
  | boundOutput =>
      exact Late.NativeStep.open (by decide) Late.NativeStep.prefixOutput
  | lateInput =>
      exact Late.NativeStep.prefixInput
  | communication =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_communication_native
  | openClose =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_open_close_native
  | restriction =>
      simpa [readyProcess, firstAction, firstTarget, Action.erase,
        Proc.erase] using
        piAdequate_erases_to_standard_late_native PiAdequate.restriction
  | scopeExtrusion =>
      exact Late.NativeStep.open (by decide) Late.NativeStep.prefixOutput
  | delegation =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_reconnect_native
  | choiceLeft =>
      exact Late.NativeStep.choiceLeft Late.NativeStep.prefixTau
  | choiceRight =>
      exact Late.NativeStep.choiceRight Late.NativeStep.prefixTau
  | matchSuccess =>
      exact Late.NativeStep.matchGuard Late.NativeStep.prefixTau
  | mismatchGuard =>
      exact Late.NativeStep.mismatchGuard (by decide)
        Late.NativeStep.prefixTau
  | dynamicPartnerAdmission =>
      exact Late.NativeStep.prefixInput
  | instanceReconnect =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_reconnect_native
  | instanceDeleteQuiescent =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_quiescent_delete_native

/-- Exact classification of every native derivative of every ready state. -/
theorem ready_native_exact
    (event : SourceEvent)
    {action : Raw.Action} {target : Raw.Proc}
    (step : Late.NativeStep (readyProcess event) action target) :
    action = firstAction event ∧ target = firstTarget event := by
  cases event with
  | freeOutput =>
      simpa [readyProcess, firstAction, firstTarget, messageSender,
        sessionChannel, Proc.erase] using send_native_exact step
  | boundOutput =>
      simpa [readyProcess, firstAction, firstTarget, delegationChannel] using
        restricted_self_send_native_exact
          (fresh := delegated) (channel := delegationBus) (by decide) step
  | lateInput =>
      simpa [readyProcess, firstAction, firstTarget, messageReceiver,
        sessionChannel, Proc.erase] using receive_native_exact step
  | communication =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_communication_native_exact step
  | openClose =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_open_close_native_exact step
  | restriction =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_restriction_native_exact step
  | scopeExtrusion =>
      simpa [readyProcess, firstAction, firstTarget, publicChannel] using
        restricted_self_send_native_exact
          (fresh := session) (channel := publicName) (by decide) step
  | delegation =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_reconnect_native_exact step
  | choiceLeft =>
      simpa [readyProcess, firstAction, firstTarget] using
        choice_left_native_exact step
  | choiceRight =>
      simpa [readyProcess, firstAction, firstTarget] using
        choice_right_native_exact step
  | matchSuccess =>
      simpa [readyProcess, firstAction, firstTarget] using
        match_native_exact step
  | mismatchGuard =>
      simpa [readyProcess, firstAction, firstTarget] using
        mismatch_native_exact' (by decide) step
  | dynamicPartnerAdmission =>
      simpa [readyProcess, firstAction, firstTarget,
        delegationChannel, Proc.erase] using receive_native_exact step
  | instanceReconnect =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_reconnect_native_exact step
  | instanceDeleteQuiescent =>
      simpa [readyProcess, firstAction, firstTarget] using
        closed_quiescent_delete_native_exact step

theorem established_native :
    Late.NativeStep closedOpenCloseTarget.erase .tau
      closedCompletedProcess.erase :=
  P1cMultistageNativeCandidate.established_native

theorem established_native_exact
    {action : Raw.Action} {target : Raw.Proc}
    (step : Late.NativeStep closedOpenCloseTarget.erase action target) :
    action = .tau ∧ target = closedCompletedProcess.erase :=
  P1cMultistageNativeCandidate.established_native_exact step

/-- The admitted phase is literally the canonical reconnect-ready process. -/
theorem admission_established_native :
    Late.NativeStep closedReconnectSource.erase .tau
      closedReconnectTarget.erase :=
  closed_reconnect_native

/-- Reconnect is the only native derivative of the admitted phase. -/
theorem admission_established_native_exact
    {action : Raw.Action} {target : Raw.Proc}
    (step : Late.NativeStep closedReconnectSource.erase action target) :
    action = .tau ∧ target = closedReconnectTarget.erase :=
  closed_reconnect_native_exact step

private theorem completed_no_native
    {action : Raw.Action} {next : Raw.Proc} :
    ¬ Late.NativeStep closedCompletedProcess.erase action next := by
  simpa only [P1cMultistageNativeCandidate.mapState] using
    (P1cMultistageNativeCandidate.payload_complete_no_native
      (action := action) (next := next))

theorem terminal_no_native
    (event : SourceEvent)
    {action : Raw.Action} {target : Raw.Proc} :
    ¬ Late.NativeStep (terminalProcess event) action target := by
  cases event with
  | communication =>
      simpa [terminalProcess] using
        closed_communication_target_no_native
          (action := action) (next := target)
  | openClose | restriction =>
      simpa [terminalProcess] using
        (completed_no_native (action := action) (next := target))
  | delegation | dynamicPartnerAdmission | instanceReconnect =>
      simpa [terminalProcess] using
        closed_reconnect_target_no_native
          (action := action) (next := target)
  | instanceDeleteQuiescent =>
      simpa [terminalProcess] using
        closed_quiescent_delete_target_no_native
          (action := action) (next := target)
  | freeOutput | boundOutput | lateInput | scopeExtrusion | choiceLeft |
      choiceRight | matchSuccess | mismatchGuard =>
      simpa [terminalProcess] using
        (zero_no_native (action := action) (target := target))

private theorem process_with_native_not_terminal
    (family : SourceEvent) {process : Raw.Proc}
    {action : Raw.Action} {next : Raw.Proc}
    (step : Late.NativeStep process action next) :
    process ≠ terminalProcess family := by
  intro equality
  apply terminal_no_native family
  simpa [equality] using step

private theorem afterFirst_process (event : SourceEvent) :
    stateProcess (afterFirst event) = firstTarget event := by
  cases event <;> rfl

private theorem step_preserves_family
    {source : State} {event : Event} {target : State}
    (step : Step source event target) :
    stateFamily source = stateFamily target := by
  cases step with
  | execute event => cases event <;> rfl
  | openClosePayload | restrictionPayload | admissionReconnect => rfl

private theorem map_afterFirst (event : SourceEvent) :
    mapState (afterFirst event) = ⟨event, firstTarget event⟩ := by
  cases event <;> rfl

private theorem target_endpoint_of_source_step
    {source : State} {event : Event} {sourceTarget : State}
    {next : Raw.Proc}
    (step : Step source event sourceTarget)
    (endpoint : stateProcess sourceTarget = next) :
    (⟨stateFamily source, next⟩ : TargetState) = mapState sourceTarget := by
  cases step with
  | execute family =>
      cases family <;> simp_all [mapState, stateFamily, stateProcess,
        afterFirst]
  | openClosePayload | restrictionPayload | admissionReconnect =>
      simp_all [mapState, stateFamily, stateProcess]

theorem native_sound
    {source : State} {event : Event} {target : State}
    (step : Step source event target) :
    Late.NativeStep
      (stateProcess source) (mapEvent event) (stateProcess target) := by
  cases step with
  | execute event =>
      change
        Late.NativeStep (readyProcess event) (firstAction event)
          (stateProcess (afterFirst event))
      rw [afterFirst_process]
      exact first_native event
  | openClosePayload =>
      exact established_native
  | restrictionPayload =>
      simpa [stateProcess, terminalProcess, mapEvent, closedOpenCloseTarget,
        closedHandshakeResult] using
        established_native
  | admissionReconnect =>
      exact admission_established_native

/--
Every native transition from every mapped source state is exactly one source
transition.  This is exhaustiveness for the complete target relation.
-/
theorem native_reflect
    {source : State} {action : Raw.Action} {target : Raw.Proc}
    (step : Late.NativeStep (stateProcess source) action target) :
    ∃ event sourceTarget,
      Step source event sourceTarget ∧
      mapEvent event = action ∧
      stateProcess sourceTarget = target := by
  cases source with
  | ready family =>
      rcases ready_native_exact family step with ⟨actionEq, targetEq⟩
      subst action
      subst target
      exact ⟨.execute family, afterFirst family, .execute family, rfl, by
        cases family <;> rfl⟩
  | openCloseEstablished =>
      rcases established_native_exact step with ⟨actionEq, targetEq⟩
      subst action
      subst target
      exact
        ⟨.openClosePayload, .completed .openClose,
          .openClosePayload, rfl, rfl⟩
  | restrictionEstablished =>
      have normalized :
          Late.NativeStep closedOpenCloseTarget.erase action target := by
        simpa [stateProcess, closedOpenCloseTarget, closedHandshakeResult]
          using step
      rcases established_native_exact normalized with ⟨actionEq, targetEq⟩
      subst action
      subst target
      exact
        ⟨.restrictionPayload, .completed .restriction,
          .restrictionPayload, rfl, rfl⟩
  | admissionEstablished =>
      rcases admission_established_native_exact step with
        ⟨actionEq, targetEq⟩
      subst action
      subst target
      exact
        ⟨.admissionReconnect, .completed .dynamicPartnerAdmission,
          .admissionReconnect, rfl, rfl⟩
  | completed family =>
      exact False.elim (terminal_no_native family step)

/-! ## Complete projection certificate -/

theorem source_success_iff_target (state : State) :
    targetLTS.success (mapState state) ↔ sourceLTS.success state := by
  cases state with
  | ready event =>
      have notTerminal :
          readyProcess event ≠ terminalProcess event :=
        process_with_native_not_terminal event (first_native event)
      simp [targetLTS, targetSuccess, mapState, stateFamily, stateProcess,
        sourceLTS, sourceSuccess, notTerminal]
  | openCloseEstablished =>
      have notTerminal :
          closedOpenCloseTarget.erase ≠ terminalProcess .openClose :=
        process_with_native_not_terminal .openClose established_native
      simp [targetLTS, targetSuccess, mapState, stateFamily, stateProcess,
        sourceLTS, sourceSuccess, notTerminal]
  | restrictionEstablished =>
      have restrictionNative :
          Late.NativeStep closedHandshakeResult.erase .tau
            closedCompletedProcess.erase := by
        simpa [closedOpenCloseTarget, closedHandshakeResult] using
          established_native
      have notTerminal :
          closedHandshakeResult.erase ≠ terminalProcess .restriction :=
        process_with_native_not_terminal .restriction restrictionNative
      simp [targetLTS, targetSuccess, mapState, stateFamily, stateProcess,
        sourceLTS, sourceSuccess, notTerminal]
  | admissionEstablished =>
      have notTerminal :
          closedReconnectSource.erase ≠
            terminalProcess .dynamicPartnerAdmission :=
        process_with_native_not_terminal .dynamicPartnerAdmission
          admission_established_native
      simp [targetLTS, targetSuccess, mapState, stateFamily, stateProcess,
        sourceLTS, sourceSuccess, notTerminal]
  | completed event =>
      simp [sourceLTS, sourceSuccess, targetLTS, targetSuccess, mapState,
        stateFamily, stateProcess]

theorem source_version_preserved (state : State) :
    targetLTS.signatureVersion (mapState state) =
      sourceLTS.signatureVersion state := by
  cases state with
  | ready event =>
      have notTerminal :
          readyProcess event ≠ terminalProcess event :=
        process_with_native_not_terminal event (first_native event)
      have dynamicReadyNeFirst :
          readyProcess .dynamicPartnerAdmission ≠
            firstTarget .dynamicPartnerAdmission := by
        intro collapsed
        have inputStep := first_native .dynamicPartnerAdmission
        rw [collapsed] at inputStep
        have actionEq :=
          (closed_reconnect_native_exact inputStep).1
        cases actionEq
      cases event <;>
        simp_all [targetLTS, targetVersion, mapState, stateFamily, stateProcess,
          sourceLTS, sourceVersion]
  | openCloseEstablished | restrictionEstablished =>
      rfl
  | admissionEstablished =>
      simp [targetLTS, targetVersion, mapState, stateFamily, stateProcess,
        sourceLTS, sourceVersion, firstTarget]
  | completed event =>
      cases event <;>
        simp [targetLTS, targetVersion, mapState, stateFamily, stateProcess,
          sourceLTS, sourceVersion, terminalProcess]

/--
All fifteen original event families, plus the two payload follow-ups and the
explicit admission/reconnect follow-up, form one projection into the complete
raw native late LTS.
-/
def certificate : ProjectionCertificate sourceLTS targetLTS where
  mapState := mapState
  mapEvent := mapEvent
  Lift := fun sourceEvent targetAction =>
    mapEvent sourceEvent = targetAction
  lift_chosen := by
    intro event
    rfl
  map_equiv := by
    intro source target equality
    subst target
    rfl
  sound := by
    intro source event target observableStep
    refine ⟨?_, trivial⟩
    cases observableStep.1 with
    | execute family =>
        rw [map_afterFirst]
        exact TargetStep.native family (first_native family)
    | openClosePayload =>
        exact TargetStep.native .openClose established_native
    | restrictionPayload =>
        exact TargetStep.native .restriction (native_sound .restrictionPayload)
    | admissionReconnect =>
        exact
          TargetStep.native .dynamicPartnerAdmission
            admission_established_native
  reflect := by
    intro source action target observableStep
    rcases observableStep.1 with ⟨family, native⟩
    rcases native_reflect native with
      ⟨event, sourceTarget, sourceStep, actionEq, endpoint⟩
    exact
      ⟨event, sourceTarget, ⟨sourceStep, trivial⟩,
        actionEq, by
          exact target_endpoint_of_source_step sourceStep endpoint⟩
  success_iff := source_success_iff_target
  waiting_iff := by
    intro state
    rfl
  signatureVersion_preserved := source_version_preserved

end Cantilune.Pi.P1cFullNativeRefinement
