import Cantilune.Core.OpenHypergraphNormalizationFunctor
import Cantilune.Core.DPOConcurrency

/-!
# Concurrency for normalized concrete open-hypergraph matches

This module connects three independently proved layers:

1. a globally injective concrete open-hypergraph morphism normalizes to a
   monic match in the ambient typed-presheaf slice;
2. the ordinary gluing condition constructs the canonical ambient DPO
   derivation for that match; and
3. two such derivations satisfying the standard explicit
   `ParallelIndependent` factorisations yield residual derivations and a
   canonical concurrency diamond.

Parallel independence remains an input. No equivalence with the whole finite
typed-presheaf slice, unconditional independence, confluence, or critical-pair
completeness is claimed.
-/

noncomputable section

namespace Cantilune.Core.OpenHypergraphNormalizationConcurrency

open CategoryTheory
open Cantilune.Core.FinitePresheafDPOI

variable {σ : FinSignature} {inputTypes outputTypes : List σ.Obj}

/--
The canonical ambient presheaf DPO derivation selected by a normalized
globally injective concrete match and its gluing proof.
-/
noncomputable def normalizedCanonicalDerivation
    {Node Edge HostNode HostEdge : Type}
    [DecidableEq Node] [DecidableEq Edge]
    [DecidableEq HostNode] [DecidableEq HostEdge]
    {leftGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes Node Edge}
    {hostGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes HostNode HostEdge}
    {rule :
      AdhesiveDPOI.Rule
        (typeGraph σ inputTypes outputTypes)}
    (leftIdentification :
      rule.left =
        (OpenHypergraphNormalization.TypedOpenHypergraph.normalize
          leftGraph).encoded)
    (matching : TypedOpenHypergraph.Monomorphism leftGraph hostGraph)
    (legal :
      PresheafComplementDPO.Presheaf.LegalMatch rule
        (OpenHypergraphNormalizationFunctor.TypedOpenHypergraph.normalizedMatch
          leftIdentification matching)) :
    AdhesiveDPOI.Derivation rule
      (OpenHypergraphNormalizationFunctor.TypedOpenHypergraph.normalizedMatch
        leftIdentification matching) :=
  OpenCospanDPOI.Presheaf.canonicalDerivation legal

/--
The retained object of the normalized derivation is definitionally the
canonical retained-subpresheaf complement generated by the gluing proof.
-/
theorem normalizedCanonicalDerivation_complement
    {Node Edge HostNode HostEdge : Type}
    [DecidableEq Node] [DecidableEq Edge]
    [DecidableEq HostNode] [DecidableEq HostEdge]
    {leftGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes Node Edge}
    {hostGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes HostNode HostEdge}
    {rule :
      AdhesiveDPOI.Rule
        (typeGraph σ inputTypes outputTypes)}
    (leftIdentification :
      rule.left =
        (OpenHypergraphNormalization.TypedOpenHypergraph.normalize
          leftGraph).encoded)
    (matching : TypedOpenHypergraph.Monomorphism leftGraph hostGraph)
    (legal :
      PresheafComplementDPO.Presheaf.LegalMatch rule
        (OpenHypergraphNormalizationFunctor.TypedOpenHypergraph.normalizedMatch
          leftIdentification matching)) :
    (normalizedCanonicalDerivation
        leftIdentification matching legal).complement =
      PresheafComplementDPO.Presheaf.complement legal :=
  OpenCospanDPOI.Presheaf.canonicalDerivation_complement_is_canonical legal

/--
Two legal normalized concrete matches enter the general DPO concurrency
theorem once the standard parallel-independence factorisations are supplied.

The conclusion exposes both residual derivations and the canonical
result-isomorphism equations preserving the images of both rule right-hand
sides.
-/
theorem normalized_parallel_independent_concurrency
    {FirstNode FirstEdge SecondNode SecondEdge HostNode HostEdge : Type}
    [DecidableEq FirstNode] [DecidableEq FirstEdge]
    [DecidableEq SecondNode] [DecidableEq SecondEdge]
    [DecidableEq HostNode] [DecidableEq HostEdge]
    {firstGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes FirstNode FirstEdge}
    {secondGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes SecondNode SecondEdge}
    {hostGraph :
      TypedOpenHypergraph
        σ inputTypes outputTypes HostNode HostEdge}
    {firstRule secondRule :
      AdhesiveDPOI.Rule
        (typeGraph σ inputTypes outputTypes)}
    (firstLeft :
      firstRule.left =
        (OpenHypergraphNormalization.TypedOpenHypergraph.normalize
          firstGraph).encoded)
    (secondLeft :
      secondRule.left =
        (OpenHypergraphNormalization.TypedOpenHypergraph.normalize
          secondGraph).encoded)
    (firstMatching :
      TypedOpenHypergraph.Monomorphism firstGraph hostGraph)
    (secondMatching :
      TypedOpenHypergraph.Monomorphism secondGraph hostGraph)
    (firstLegal :
      PresheafComplementDPO.Presheaf.LegalMatch firstRule
        (OpenHypergraphNormalizationFunctor.TypedOpenHypergraph.normalizedMatch
          firstLeft firstMatching))
    (secondLegal :
      PresheafComplementDPO.Presheaf.LegalMatch secondRule
        (OpenHypergraphNormalizationFunctor.TypedOpenHypergraph.normalizedMatch
          secondLeft secondMatching))
    (independent :
      DPOConcurrency.ParallelIndependent
        (normalizedCanonicalDerivation
          firstLeft firstMatching firstLegal)
        (normalizedCanonicalDerivation
          secondLeft secondMatching secondLegal)) :
    Nonempty
        (AdhesiveDPOI.Derivation firstRule
          independent.firstResidualMatch) ∧
      Nonempty
        (AdhesiveDPOI.Derivation secondRule
          independent.secondResidualMatch) ∧
      ∃ resultIso :
          independent.firstAfterSecond.result ≅
            independent.secondAfterFirst.result,
        (independent.secondRightToFirstResidualContext ≫
            independent.firstAfterSecond.complementToResult) ≫
              resultIso.hom =
            independent.secondAfterFirst.rightToResult ∧
          independent.firstAfterSecond.rightToResult ≫ resultIso.hom =
            independent.firstRightToSecondResidualContext ≫
              independent.secondAfterFirst.complementToResult := by
  refine
    ⟨⟨independent.firstAfterSecond⟩,
      ⟨independent.secondAfterFirst⟩, ?_⟩
  exact independent.parallel_independent_concurrency

end Cantilune.Core.OpenHypergraphNormalizationConcurrency
