import Cantilune.Theorems.ProductCommonTrajectoryCertificate

/-! # Type-level regression checks for the complete common-trajectory gate -/

namespace Cantilune.Tests.ProductCommonTrajectoryCertificate

open Cantilune.Theorems.ProductCommonTrajectoryCertificate

#check CompleteProductCommonTrajectoryCertificate
#check CompleteProductCommonTrajectoryCertificate.familyExact
#check CompleteProductCommonTrajectoryCertificate.selectedNative
#check CompleteProductCommonTrajectoryCertificate.selectedReplay
#check CompleteProductCommonTrajectoryCertificate.selectedProjectedNative
#check CompleteProductCommonTrajectoryCertificate.metadataFromSelectedReplay
#check CompleteProductCommonTrajectoryCertificate.selectedRawNative
#check CompleteProductCommonTrajectoryCertificate.selectedRegistryRealizes
#check CompleteProductCommonTrajectoryCertificate.selectedRawSource
#check CompleteProductCommonTrajectoryCertificate.selectedRawDerivative
#check CompleteProductCommonTrajectoryCertificate.selectedActualFMS

#print axioms CompleteProductCommonTrajectoryCertificate.familyExact
#print axioms CompleteProductCommonTrajectoryCertificate.selectedNative
#print axioms CompleteProductCommonTrajectoryCertificate.selectedReplay
#print axioms CompleteProductCommonTrajectoryCertificate.selectedProjectedNative
#print axioms CompleteProductCommonTrajectoryCertificate.metadataFromSelectedReplay
#print axioms CompleteProductCommonTrajectoryCertificate.selectedRawNative
#print axioms CompleteProductCommonTrajectoryCertificate.selectedRegistryRealizes
#print axioms CompleteProductCommonTrajectoryCertificate.selectedRawDerivative
#print axioms CompleteProductCommonTrajectoryCertificate.selectedActualFMS

end Cantilune.Tests.ProductCommonTrajectoryCertificate
